**Set Up Environment**

In [1]:
import nltk
nltk.download('punkt')
nltk.download('stopwords')

[nltk_data] Downloading package punkt to /Users/tszyan/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     /Users/tszyan/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

**Load & Inspect the Motley Fool pkl**

In [3]:
import pandas as pd
import numpy as np

# ── Load ─────────────────────────────────────────────────────────────────────
df = pd.read_pickle('Data/motley-fool-data.pkl')

# ── Check exact column names first ───────────────────────────────────────────
print("Columns:", df.columns.tolist())

# ── Standardize column name: rename 'quarter' to 'q' if needed ───────────────
if 'quarter' in df.columns and 'q' not in df.columns:
    df = df.rename(columns={'quarter': 'q'})
    print("Renamed 'quarter' → 'q'")

# ── Basic shape & dtypes ──────────────────────────────────────────────────────
print("\nShape:", df.shape)
print("\nDtypes:\n", df.dtypes)
print("\nFirst row:\n", df.iloc[0])

# ── Null check ────────────────────────────────────────────────────────────────
print("\nNull counts:\n", df.isnull().sum())

# ── Duplicate check ───────────────────────────────────────────────────────────
for col in df.columns:
    has_list = df[col].apply(lambda x: isinstance(x, list)).any()
    if has_list:
        print(f"Column '{col}' contains lists")

for col in df.columns:
    if df[col].apply(lambda x: isinstance(x, list)).any():
        df[col] = df[col].apply(lambda x: str(x) if isinstance(x, list) else x)
        print(f"Converted '{col}' lists → strings")

print("\nDuplicate rows (exact):", df.duplicated().sum())
print("Duplicate ticker+quarter+date:", df.duplicated(subset=['ticker', 'q', 'date']).sum())

# ── Standardize q column ──────────────────────────────────────────────────────
df['q'] = df['q'].astype(str).str.strip()

# ── Tickers with 2+ quarters ──────────────────────────────────────────────────
ticker_counts = df.groupby('ticker')['q'].nunique()
usable_tickers = ticker_counts[ticker_counts >= 2]
print(f"\nTickers with 2+ quarters: {len(usable_tickers)} out of {df['ticker'].nunique()}")

# ── Flag short or empty transcripts ──────────────────────────────────────────
df['transcript_length'] = df['transcript'].fillna('').astype(str).str.len()
short_transcripts = df[df['transcript_length'] < 500]
print(f"\nTranscripts under 500 characters: {len(short_transcripts)}")
print(f"Empty transcripts: {df['transcript'].isna().sum()}")

# ── Quarter distribution ──────────────────────────────────────────────────────
print("\nQuarter distribution:\n", df['q'].value_counts().sort_index())

# ── Inspection summary ────────────────────────────────────────────────────────
print("\n── Inspection Summary ──────────────────────────────────────────")
print(f"Total rows:                      {len(df)}")
print(f"Total unique tickers:            {df['ticker'].nunique()}")
print(f"Tickers with 2+ quarters:        {len(usable_tickers)}")
print(f"Duplicate rows:                  {df.duplicated().sum()}")
print(f"Short transcripts (<500 chars):  {len(short_transcripts)}")
print(f"Quarter range:                   {df['q'].min()} to {df['q'].max()}")

Columns: ['date', 'exchange', 'q', 'ticker', 'transcript']

Shape: (18755, 5)

Dtypes:
 date          object
exchange      object
q             object
ticker        object
transcript    object
dtype: object

First row:
 date                                 Aug 27, 2020, 9:00 p.m. ET
exchange                                           NASDAQ: BILI
q                                                       2020-Q2
ticker                                                     BILI
transcript    Prepared Remarks:\nOperator\nGood day, and wel...
Name: 0, dtype: object

Null counts:
 date          0
exchange      0
q             0
ticker        0
transcript    0
dtype: int64
Column 'date' contains lists
Converted 'date' lists → strings

Duplicate rows (exact): 1156
Duplicate ticker+quarter+date: 1198

Tickers with 2+ quarters: 2658 out of 2876

Transcripts under 500 characters: 0
Empty transcripts: 0

Quarter distribution:
 q
2017-Q3       1
2017-Q4      15
2018-Q1       7
2018-Q2      16
2018-Q3  

**Parse the Date Column**

In [4]:
from dateutil import parser as dateutil_parser
import re

# ── Confirm date and q columns exist before proceeding ────────────────────────
assert 'date' in df.columns, "ERROR: 'date' column not found. Check df.columns."
assert 'q' in df.columns,    "ERROR: 'q' column not found. Check df.columns."

# ── Improved timezone stripper (handles lowercase, punctuation, mid-string) ───
def strip_timezone(date_str):
    """Remove common US timezone suffixes from date strings."""
    return re.sub(
        r'\s+(ET|EST|EDT|CT|CST|CDT|PT|PST|PDT|MT|MST|MDT)\.?$',
        '', str(date_str).strip(), flags=re.IGNORECASE
    )

# ── Primary parser: dateutil with fuzzy matching ──────────────────────────────
def parse_date_primary(date_str):
    try:
        cleaned = strip_timezone(date_str)
        return dateutil_parser.parse(cleaned, fuzzy=True)
    except Exception:
        return None

# ── Fallback parser: derive approximate date from q column ───────────────────
# Maps quarter to first month of that quarter
QUARTER_TO_MONTH = {'Q1': '01', 'Q2': '04', 'Q3': '07', 'Q4': '10'}

def parse_date_fallback(q_str):
    try:
        year, quarter = str(q_str).strip().split('-')
        month = QUARTER_TO_MONTH.get(quarter.upper(), '01')
        return pd.Timestamp(f"{year}-{month}-01")
    except Exception:
        return pd.NaT

# ── Apply primary parser ──────────────────────────────────────────────────────
print("Parsing date column...")
primary_parsed = df['date'].apply(parse_date_primary)
fallback_needed = primary_parsed.isna()

print(f"  Primary parse succeeded: {(~fallback_needed).sum()} rows")
print(f"  Fallback needed:         {fallback_needed.sum()} rows")

# ── Apply fallback where primary failed ───────────────────────────────────────
fallback_parsed = df.loc[fallback_needed, 'q'].apply(parse_date_fallback)

# ── Combine into earnings_date column ────────────────────────────────────────
df['earnings_date'] = primary_parsed
df.loc[fallback_needed, 'earnings_date'] = fallback_parsed

# ── Track parse method and whether date is approximate ───────────────────────
df['date_parse_method'] = 'primary'
df.loc[fallback_needed, 'date_parse_method'] = 'fallback'
df['earnings_date_is_approx'] = fallback_needed  # True = approximate quarter start date

# ── Check results ─────────────────────────────────────────────────────────────
still_failed = df['earnings_date'].isna()
print(f"  Still unparseable after fallback: {still_failed.sum()} rows")

print("\nSample parsed dates:")
print(df[['date', 'q', 'earnings_date', 'date_parse_method', 'earnings_date_is_approx']]
      .head(10).to_string())

print("\nDate range:")
print(f"  Earliest: {df['earnings_date'].min()}")
print(f"  Latest:   {df['earnings_date'].max()}")

print(f"\nApproximate dates (fallback): {df['earnings_date_is_approx'].sum()} rows")
print(f"Exact dates (primary):        {(~df['earnings_date_is_approx']).sum()} rows")

# ── Drop rows that completely failed to parse ─────────────────────────────────
df_before = len(df)
df = df[df['earnings_date'].notna()].copy()
print(f"\nDropped {df_before - len(df)} rows with unparseable dates.")
print(f"Remaining rows: {len(df)}")

# ── Save checkpoint ───────────────────────────────────────────────────────────
df.to_csv('Data/data_dates_parsed.csv', index=False)
print("\nSaved: data_dates_parsed.csv")

Parsing date column...
  Primary parse succeeded: 18375 rows
  Fallback needed:         380 rows
  Still unparseable after fallback: 0 rows

Sample parsed dates:
                          date        q       earnings_date date_parse_method  earnings_date_is_approx
0   Aug 27, 2020, 9:00 p.m. ET  2020-Q2 2020-08-27 21:00:00           primary                    False
1   Jul 30, 2020, 4:30 p.m. ET  2020-Q3 2020-07-30 16:30:00           primary                    False
2   Oct 23, 2019, 5:00 p.m. ET  2020-Q1 2019-10-23 17:00:00           primary                    False
3   Nov 6, 2019, 12:00 p.m. ET  2019-Q3 2019-11-06 12:00:00           primary                    False
4    Aug 7, 2019, 8:30 a.m. ET  2019-Q2 2019-08-07 08:30:00           primary                    False
5    Nov 4, 2020, 5:00 p.m. ET  2020-Q3 2020-11-04 17:00:00           primary                    False
6    Aug 5, 2020, 8:30 a.m. ET  2020-Q2 2020-08-05 08:30:00           primary                    False
7  Mar 24, 202

**Clean the Transcripts**

In [6]:
import re
import os

# ── Patterns to remove ────────────────────────────────────────────────────────

# Operator lines (lines that are just "Operator" or start with operator instructions)
OPERATOR_PATTERN = re.compile(
    r'(^|\n)(Operator\n|Operator:\s.*?\n)',
    flags=re.IGNORECASE
)

# Common boilerplate opening lines
BOILERPLATE_PATTERN = re.compile(
    r'(Good (day|morning|afternoon|evening)[,.].*?\n'
    r'|Thank you for stand.*?\n'
    r'|Ladies and gentlemen.*?\n'
    r'|Welcome to the.*?(conference call|earnings call).*?\n'
    r'|Please be advised.*?\n'
    r'|Your (lines have been|line is) (placed on mute|muted).*?\n'
    r'|\[Operator Instructions\].*?\n'
    r'|At this time.*?question.*?\n)',
    flags=re.IGNORECASE
)

# Forward-looking statement disclaimers
FORWARD_LOOKING_PATTERN = re.compile(
    r'(This (conference call|presentation|discussion) contains? forward.looking statements?.*?(?=\n\n|\Z)'
    r'|Certain statements? (made|discussed) (today|in this).*?(?=\n\n|\Z)'
    r'|During (today\'?s?|this) (call|presentation).*?forward.looking.*?(?=\n\n|\Z))',
    flags=re.IGNORECASE | re.DOTALL
)

# Safe harbour language
SAFE_HARBOUR_PATTERN = re.compile(
    r'(Safe (Harbour|Harbor) Statement.*?(?=\n\n|\Z)'
    r'|These (statements|forward.looking statements) involve.*?(?=\n\n|\Z))',
    flags=re.IGNORECASE | re.DOTALL
)

# Excessive whitespace 
WHITESPACE_PATTERN = re.compile(r'\n{3,}')

# ── Remove actual corrupted characters ──────────────────────────────────────
ENCODING_PATTERN = re.compile(r'[\uFFFD]')

def clean_transcript(text):
    """Apply all cleaning steps to a single transcript string."""
    if not isinstance(text, str) or len(text.strip()) == 0:
        return ''

    text = FORWARD_LOOKING_PATTERN.sub('\n', text)
    text = SAFE_HARBOUR_PATTERN.sub('\n', text)
    text = OPERATOR_PATTERN.sub('\n', text)
    text = BOILERPLATE_PATTERN.sub('\n', text)
    text = ENCODING_PATTERN.sub(' ', text)
    text = WHITESPACE_PATTERN.sub('\n\n', text)
    text = text.strip()

    return text

# ── Apply to full dataframe ───────────────────────────────────────────────────
print("Cleaning transcripts...")
df['transcript_clean'] = df['transcript'].fillna('').apply(clean_transcript)
df['transcript_clean_length'] = df['transcript_clean'].str.len()

# ── Safe division — avoid crash if transcript_length = 0 ──────────────────────
reduction_pct = np.where(
    df['transcript_length'] > 0,
    (df['transcript_length'] - df['transcript_clean_length'])
    / df['transcript_length'] * 100,
    np.nan
)

print(f"\nBefore cleaning — avg length: {df['transcript_length'].mean():.0f} chars")
print(f"After cleaning  — avg length: {df['transcript_clean_length'].mean():.0f} chars")
print(f"Reduction: {np.nanmean(reduction_pct):.1f}%")

# Flag transcripts that became too short after cleaning
too_short_after = df[df['transcript_clean_length'] < 200]
print(f"\nTranscripts under 200 chars after cleaning: {len(too_short_after)}")
print("Sample tickers affected:", too_short_after['ticker'].head(5).tolist())

# ── Spot check — compare before and after for one transcript ──────────────────
sample_idx = 0
print("\n── BEFORE cleaning (first 500 chars) ──────────────────────────────────")
print(df['transcript'].iloc[sample_idx][:500])
print("\n── AFTER cleaning (first 500 chars) ───────────────────────────────────")
print(df['transcript_clean'].iloc[sample_idx][:500])

# ── Save checkpoint ───────────────────────────────────────────────────────────
df.to_csv('Data/data_transcripts_cleaned.csv', index=False)
print("\nSaved: data_transcripts_cleaned.csv")

Cleaning transcripts...

Before cleaning — avg length: 47303 chars
After cleaning  — avg length: 30943 chars
Reduction: 34.5%

Transcripts under 200 chars after cleaning: 1511
Sample tickers affected: ['SJM', 'BC', 'MSTR', 'CENT', 'DFIN']

── BEFORE cleaning (first 500 chars) ──────────────────────────────────
Prepared Remarks:
Operator
Good day, and welcome to the Bilibili 2020 Second Quarter Earnings Conference Call. Today's conference is being recorded.
At this time, I would like to turn the conference over to Juliet Yang, Senior Director of Investor Relations. Please go ahead.
Juliet Yang -- Senior Director of Investor Relations
Thank you, operator.
Please note the discussion today will contain forward-looking statements relating to the Company's future performance, and are intended to qualify for

── AFTER cleaning (first 500 chars) ───────────────────────────────────
Prepared Remarks:

At this time, I would like to turn the conference over to Juliet Yang, Senior Director of Inves

**Build the Speaker-Tag Parser**

In [7]:
import os

# ── Part A: Study ramssvimala format ──────────────────────────────────────────
NLP_DATASET_PATH = './Data/archive/NLP_Dataset'

def read_sample_transcripts(folder_path, n_files=5):
    """Read first n_files from the NLP_Dataset to study speaker tag format."""
    samples = []
    count = 0
    for root, dirs, files in os.walk(folder_path):
        for fname in files:
            if fname.endswith('.txt') and count < n_files:
                fpath = os.path.join(root, fname)
                with open(fpath, 'r', encoding='utf-8', errors='ignore') as f:
                    content = f.read()
                samples.append({'file': fpath, 'content': content})
                count += 1
    return samples

print("Reading sample transcripts from NLP_Dataset...")
samples = read_sample_transcripts(NLP_DATASET_PATH, n_files=5)

# Print first 1000 chars of each to study the speaker tag format
for s in samples:
    print(f"\n── File: {s['file']} ──────────────────────────────")
    print(s['content'][:1000])
    print("...")

Reading sample transcripts from NLP_Dataset...

── File: ./Data/archive/NLP_Dataset/Cardinal Health/2023_Q3_cah.txt ──────────────────────────────
Earnings Call TranscriptEarnings Call Transcript2023-Q3Guidance21Dividend3Acquisition1Revenue10EBITDA1Free Cash Flow4Gross Margin1from
			0OperatorHello and welcome to the Third Quarter Fiscal Year 2023 Cardinal Health Incorporated Earnings Conference Call. My name is George. I'll be your coordinator for today's event. Please note this conference is being recorded, and for the duration of the call, your lines will be in a listen-only mode. However, you will have the opportunity to ask questions at the end of the presentation. [Operator Instructions]And I would now like to hand the call over to your host today. Mr. Kevin Moran, Vice President of Investor Relations, to begin today's conference. Please go ahead, sir.KKevin MoranVice President, Investor RelationsGood morning. Today we will discuss Cardinal Health's third quarter fiscal 2023 resu

In [19]:
# ── Part B: Parser for ramssvimala actual format ──────────────────────────────

EXEC_TITLES = (
    r'Chief Executive Officer|CEO|Chief Financial Officer|CFO|'
    r'Chief Operating Officer|COO|President|Chairman|Founder|'
    r'Chief Technology Officer|CTO|Chief Revenue Officer|CRO|'
    r'Executive Vice President|Senior Vice President|Vice President|'
    r'EVP|SVP|VP|Chief Accounting Officer|Chief Legal Officer|'
    r'Chief Marketing Officer|Chief Strategy Officer|'
    r'Investor Relations|Director'
)

ANALYST_TITLES = (
    r'Analyst|Research Analyst|Equity Research|Managing Director|'
    r'Managing Partner|Portfolio Manager|Partner|'
    r'Securities|Capital Markets|Barclays|Goldman Sachs|Morgan Stanley|'
    r'JPMorgan|Deutsche Bank|Citigroup|UBS|Wells Fargo|'
    r'Raymond James|Jefferies|Cowen|Piper|Baird|Mizuho|Oppenheimer'
)

# Match inline: single capital initial immediately followed by Title Case name + title
# e.g. "KKevin MoranVice President, Investor Relations"
SPEAKER_HEADER = re.compile(
    r'[A-Z]'                                        # single capital initial
    r'(?P<name>[A-Z][a-z]+(?:\s[A-Z][a-z]+)+)'      # Full Name in Title Case
    r'(?P<title>(?:' + EXEC_TITLES + r'|' + ANALYST_TITLES + r')'
    r'[^A-Z\n]{0,80})'                              # title text, stops at next capital block
)

# Clean title bleed from speech start
TITLE_BLEED = re.compile(
    r'^(?:' + EXEC_TITLES + r'|' + ANALYST_TITLES + r'|IR|VP|CFO|CEO|COO|CTO|Bank|Inc|Corp|Group)'
    r'[\s,&]{0,10}',
    flags=re.IGNORECASE
)

def split_into_turns(text):
    """
    Find all speaker headers inline and extract speech between them.
    Returns list of (name, title, speech) tuples.
    """
    turns = []
    headers = list(SPEAKER_HEADER.finditer(text))

    print(f"  [debug] Found {len(headers)} speaker headers")
    for h in headers[:5]:
        print(f"    → name: '{h.group('name')}' | title: '{h.group('title')[:40]}'")

    for i, match in enumerate(headers):
        name  = match.group('name').strip()
        title = match.group('title').strip()

        speech_start = match.end()
        speech_end   = headers[i + 1].start() if i + 1 < len(headers) else len(text)
        speech       = text[speech_start:speech_end].strip()

        speech = TITLE_BLEED.sub('', speech).strip()

        turns.append((name, title, speech))

    return turns

def classify_turn(name, title):
    """Return 'management', 'analyst', or 'operator'."""
    if re.search(r'operator|coordinator', name, re.IGNORECASE):
        return 'operator'
    if re.search(ANALYST_TITLES, title, re.IGNORECASE):
        return 'analyst'
    return 'management'

def parse_speakers(text):
    """
    Parse transcript into management and QA segments.
    Falls back to full transcript if no speaker headers found.
    """
    if not isinstance(text, str) or len(text.strip()) == 0:
        return {'management_text': '', 'qa_text': '', 'speaker_parse_success': False}

    turns = split_into_turns(text)

    if len(turns) == 0:
        return {
            'management_text': text,
            'qa_text': '',
            'speaker_parse_success': False
        }

    mgmt_segments = []
    qa_segments   = []

    for name, title, speech in turns:
        if not speech:
            continue
        role = classify_turn(name, title)
        if role == 'management':
            mgmt_segments.append(speech)
        elif role == 'analyst':
            qa_segments.append(speech)

    return {
        'management_text': '\n\n'.join(mgmt_segments),
        'qa_text':         '\n\n'.join(qa_segments),
        'speaker_parse_success': len(mgmt_segments) > 0 or len(qa_segments) > 0
    }

In [20]:
# ── Part C: Test parser on ramssvimala samples ────────────────────────────────
print("Testing parser on ramssvimala dataset samples...\n")
for s in samples[:3]:
    result = parse_speakers(s['content'])
    print(f"File: {s['file'].split('/')[-1]}")
    print(f"  Parse success:          {result['speaker_parse_success']}")
    print(f"  Management text length: {len(result['management_text'])} chars")
    print(f"  QA text length:         {len(result['qa_text'])} chars")
    print(f"  Management preview:     {result['management_text'][:300]}")
    print(f"  QA preview:             {result['qa_text'][:300]}")
    print()

Testing parser on ramssvimala dataset samples...

  [debug] Found 28 speaker headers
    → name: 'Kevin Moran' | title: 'Vice President, '
    → name: 'Jason Hollar' | title: 'Chief Executive Officer'
    → name: 'Aaron Alt' | title: 'Chief Financial Officer'
    → name: 'Jason Hollar' | title: 'Chief Executive Officer'
    → name: 'Jason Hollar' | title: 'Chief Executive Officer'
File: 2023_Q3_cah.txt
  Parse success:          True
  Management text length: 101377 chars
  QA text length:         3826 chars
  Management preview:     Good morning. Today we will discuss Cardinal Health's third quarter fiscal 2023 results, along with updates to our full year outlook. You can find today's press release and earnings presentation on the IR section of our website at ir.cardinalhealth.com.Joining me today are Jason Hollar, our Chief Ex
  QA preview:             Thanks very much and thanks for all the detail. Jason, I know you're going to talk about this at your Analyst Day around the portfolio

In [21]:
# ── Part D:  Apply parser to Motley Fool pkl ──────────────────────────────────
print("Applying speaker parser to Motley Fool transcripts...")

parsed = df['transcript_clean'].apply(parse_speakers)
parsed_df = pd.DataFrame(parsed.tolist())

df['management_text']       = parsed_df['management_text']
df['qa_text']               = parsed_df['qa_text']
df['speaker_parse_success'] = parsed_df['speaker_parse_success']

# ── Check success rate ────────────────────────────────────────────────────────
success_rate = df['speaker_parse_success'].mean() * 100
print(f"Speaker parse success rate: {success_rate:.1f}%")
print(f"  Successfully parsed: {df['speaker_parse_success'].sum()} rows")
print(f"  Fell back to full transcript: {(~df['speaker_parse_success']).sum()} rows")

if success_rate < 30:
    print("\nNOTE: Low parse rate on Motley Fool pkl.")
    print("Fallback applied: management_text = full transcript for unparsed rows.")
    mask = ~df['speaker_parse_success']
    df.loc[mask, 'management_text'] = df.loc[mask, 'transcript_clean']

# ── Length check on parsed segments ──────────────────────────────────────────
df['management_text_length'] = df['management_text'].str.len()
df['qa_text_length']         = df['qa_text'].str.len()

print(f"\nAvg management text length: {df['management_text_length'].mean():.0f} chars")
print(f"Avg QA text length:           {df['qa_text_length'].mean():.0f} chars")

# ── Safe spot check — won't crash if no rows parsed successfully ─────────────
parsed_rows = df[df['speaker_parse_success'] == True]

if len(parsed_rows) > 0:
    sample = parsed_rows.iloc[0]
    print(f"\n── Sample parsed transcript (ticker: {sample['ticker']}) ──────────────")
    print(f"Management text preview:\n{sample['management_text'][:300]}")
    print(f"\nQA text preview:\n{sample['qa_text'][:300]}")
else:
    print("\nNo successfully parsed transcripts found for spot check.")
    print("This is expected if Motley Fool format differs from ramssvimala.")

# ── Save checkpoint ───────────────────────────────────────────────────────────
df.to_csv('Data/data_speakers_parsed.csv', index=False)
print("\nSaved: Data/data_speakers_parsed.csv")

Applying speaker parser to Motley Fool transcripts...
  [debug] Found 0 speaker headers
  [debug] Found 0 speaker headers
  [debug] Found 0 speaker headers
  [debug] Found 0 speaker headers
  [debug] Found 0 speaker headers
  [debug] Found 0 speaker headers
  [debug] Found 0 speaker headers
  [debug] Found 0 speaker headers
  [debug] Found 0 speaker headers
  [debug] Found 0 speaker headers
  [debug] Found 0 speaker headers
  [debug] Found 0 speaker headers
  [debug] Found 0 speaker headers
  [debug] Found 0 speaker headers
  [debug] Found 0 speaker headers
  [debug] Found 0 speaker headers
  [debug] Found 0 speaker headers
  [debug] Found 0 speaker headers
  [debug] Found 0 speaker headers
  [debug] Found 0 speaker headers
  [debug] Found 0 speaker headers
  [debug] Found 0 speaker headers
  [debug] Found 0 speaker headers
  [debug] Found 0 speaker headers
  [debug] Found 0 speaker headers
  [debug] Found 0 speaker headers
  [debug] Found 0 speaker headers
  [debug] Found 0 speaker he

**Note on Speaker-Level Parsing:** 
The speaker-tag parser was developed and validated on the ramssvimala dataset (NLP_Dataset), where it successfully separates CEO/CFO prepared remarks from analyst Q&A with a high parse rate. However, the Motley Fool pkl transcripts use a different formatting convention, resulting in a 0% parse rate on that dataset. As a result, the full transcript is currently used as a fallback for all 18,755 rows in the Motley Fool corpus. This is an acceptable starting point. Speaker-level parsing for the Motley Fool pkl will be revisited at the beginning of Phase 2, once the FinBERT pipeline is operational. At that point, a side-by-side comparison will be run on a sample of 50–100 transcripts to determine whether isolating management speech produces meaningfully different sentiment scores. If the improvement is material, the parser will be updated and sentiment features will be re-generated before full-scale training.

**Fetch Stock Price Data via yfinance**

In [22]:
import yfinance as yf
import pandas as pd
import numpy as np
import os
import time

df = pd.read_csv('Data/data_speakers_parsed.csv')

# ── Get all unique tickers from the pkl ──────────────────────────────────────
tickers = df['ticker'].dropna().unique().tolist()
print(f"Total unique tickers to fetch: {len(tickers)}")

# ── Fetch price data for all tickers ─────────────────────────────────────────
BATCH_SIZE = 50
all_prices = []
failed_tickers = []

print(f"\nFetching price data in batches of {BATCH_SIZE}...")

for i in range(0, len(tickers), BATCH_SIZE):
    batch = tickers[i:i + BATCH_SIZE]
    batch_str = ' '.join(batch)
    
    try:
        data = yf.download(
            batch_str,
            start='2017-01-01',
            end='2024-01-01',
            auto_adjust=True,
            progress=False
        )
        
        # Extract just the Close prices
        if isinstance(data.columns, pd.MultiIndex):
            # Multiple tickers — columns are (field, ticker)
            close_data = data['Close']
        else:
            # Single ticker returned as flat DataFrame
            close_data = data[['Close']]
            close_data.columns = [batch[0]]
        
        close_long = close_data.reset_index().melt(
            id_vars='Date',
            var_name='ticker',
            value_name='close'
        )
        close_long = close_long.dropna(subset=['close'])
        all_prices.append(close_long)
        
        print(f"  Batch {i//BATCH_SIZE + 1}/{(len(tickers)-1)//BATCH_SIZE + 1}: "
              f"fetched {len(batch)} tickers, "
              f"{len(close_long)} price rows")
        
        time.sleep(0.5)
        
    except Exception as e:
        print(f"  Batch {i//BATCH_SIZE + 1} failed: {e}")
        failed_tickers.extend(batch)

# ── Combine all price data ────────────────────────────────────────────────────
print("\nCombining all price data...")
price_df = pd.concat(all_prices, ignore_index=True)
price_df['Date'] = pd.to_datetime(price_df['Date'])
price_df = price_df.sort_values(['ticker', 'Date']).reset_index(drop=True)

# ── Check results ─────────────────────────────────────────────────────────────
print(f"\nPrice data shape: {price_df.shape}")
print(f"Unique tickers with price data: {price_df['ticker'].nunique()}")
print(f"Date range: {price_df['Date'].min()} to {price_df['Date'].max()}")
print(f"Failed tickers: {len(failed_tickers)}")
print(f"\nSample:\n{price_df.head(10).to_string()}")

# ── Flag tickers that returned no data (delisted / invalid) ───────────────────
tickers_with_prices = set(price_df['ticker'].unique())
tickers_without_prices = [t for t in tickers if t not in tickers_with_prices]
print(f"\nTickers with no price data (delisted/invalid): {len(tickers_without_prices)}")
print(f"Usable ticker universe: {len(tickers_with_prices)}")

# ── Save price data ───────────────────────────────────────────────────────────
price_df.to_csv('Data/stock_prices.csv', index=False)
print("\nSaved: Data/stock_prices.csv")

# ── Fetch S&P 500 benchmark separately ───────────────────────────────────────
print("\nFetching S&P 500 benchmark (^GSPC)...")
sp500 = yf.download('^GSPC', start='2017-01-01', end='2024-01-01',
                    auto_adjust=True, progress=False)
sp500 = sp500[['Close']].reset_index()
sp500.columns = ['Date', 'sp500_close']
sp500['Date'] = pd.to_datetime(sp500['Date'])
sp500.to_csv('Data/sp500_prices.csv', index=False)
print(f"S&P 500 rows: {len(sp500)}")
print(f"Sample:\n{sp500.head(5).to_string()}")
print("\nSaved: Data/sp500_prices.csv")

Total unique tickers to fetch: 2876

Fetching price data in batches of 50...


$FL: possibly delisted; no timezone found
$MYOV: possibly delisted; no timezone found
HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: WBA"}}}
$WBA: possibly delisted; no timezone found
$COUP: possibly delisted; no timezone found
$KAR: possibly delisted; no timezone found
$BCOV: possibly delisted; no timezone found
$WDR: possibly delisted; no timezone found

7 Failed downloads:
['FL', 'MYOV', 'WBA', 'COUP', 'KAR', 'BCOV', 'WDR']: possibly delisted; no timezone found


  Batch 1/58: fetched 50 tickers, 71097 price rows


$AYX: possibly delisted; no timezone found
$AL: possibly delisted; no timezone found
$SGEN: possibly delisted; no timezone found
$XLNX: possibly delisted; no timezone found
$AAWW: possibly delisted; no timezone found
$OCFT: possibly delisted; no timezone found
$SIVB: possibly delisted; no timezone found
$CTIC: possibly delisted; no timezone found
$AIMC: possibly delisted; no timezone found
$CARA: possibly delisted; no timezone found

10 Failed downloads:
['AYX', 'AL', 'SGEN', 'XLNX', 'AAWW', 'OCFT', 'SIVB', 'CTIC', 'AIMC', 'CARA']: possibly delisted; no timezone found


  Batch 2/58: fetched 50 tickers, 68271 price rows


$WWE: possibly delisted; no timezone found
$STNG): possibly delisted; no timezone found
$NGD: possibly delisted; no timezone found
$ZEUS: possibly delisted; no timezone found
$BCOR: possibly delisted; no price data found  (1d 2017-01-01 -> 2024-01-01) (Yahoo error = "Data doesn't exist for startDate = 1483246800, endDate = 1704085200")
$SIX: possibly delisted; no timezone found
$CMLS: possibly delisted; no timezone found
$ICPT: possibly delisted; no timezone found
$ZUO: possibly delisted; no timezone found
$CTK: possibly delisted; no timezone found
$VLDR: possibly delisted; no timezone found
$CHS: possibly delisted; no timezone found
$ATC): possibly delisted; no timezone found
$LHCG: possibly delisted; no timezone found

14 Failed downloads:
['WWE', 'STNG)', 'NGD', 'ZEUS', 'SIX', 'CMLS', 'ICPT', 'ZUO', 'CTK', 'VLDR', 'CHS', 'ATC)', 'LHCG']: possibly delisted; no timezone found
['BCOR']: possibly delisted; no price data found  (1d 2017-01-01 -> 2024-01-01) (Yahoo error = "Data doesn't e

  Batch 3/58: fetched 50 tickers, 59152 price rows


$GMLP: possibly delisted; no timezone found
$TGNA: possibly delisted; no timezone found
$TPIC: possibly delisted; no price data found  (1d 2017-01-01 -> 2024-01-01)
$TIG: possibly delisted; no timezone found
$ITCB: possibly delisted; no timezone found
$SQ: possibly delisted; no timezone found
$NCR: possibly delisted; no timezone found
$SBNY: possibly delisted; no price data found  (1d 2017-01-01 -> 2024-01-01) (Yahoo error = "Data doesn't exist for startDate = 1483246800, endDate = 1704085200")
$HMLP: possibly delisted; no timezone found

9 Failed downloads:
['GMLP', 'TGNA', 'TIG', 'ITCB', 'SQ', 'NCR', 'HMLP']: possibly delisted; no timezone found
['TPIC']: possibly delisted; no price data found  (1d 2017-01-01 -> 2024-01-01)
['SBNY']: possibly delisted; no price data found  (1d 2017-01-01 -> 2024-01-01) (Yahoo error = "Data doesn't exist for startDate = 1483246800, endDate = 1704085200")


  Batch 4/58: fetched 50 tickers, 66750 price rows


$ATVI: possibly delisted; no timezone found
$DADA: possibly delisted; no timezone found
$ONCT: possibly delisted; no timezone found
$CDMO: possibly delisted; no timezone found
$EBIX: possibly delisted; no timezone found
$AKTS: possibly delisted; no price data found  (1d 2017-01-01 -> 2024-01-01) (Yahoo error = "Data doesn't exist for startDate = 1483246800, endDate = 1704085200")
$BGFV: possibly delisted; no timezone found
$TCS: possibly delisted; no timezone found
$NSTG: possibly delisted; no timezone found
$CPE: possibly delisted; no timezone found

10 Failed downloads:
['ATVI', 'DADA', 'ONCT', 'CDMO', 'EBIX', 'BGFV', 'TCS', 'NSTG', 'CPE']: possibly delisted; no timezone found
['AKTS']: possibly delisted; no price data found  (1d 2017-01-01 -> 2024-01-01) (Yahoo error = "Data doesn't exist for startDate = 1483246800, endDate = 1704085200")


  Batch 5/58: fetched 50 tickers, 69413 price rows


$DISC.A: possibly delisted; no timezone found
$TFFP: possibly delisted; no timezone found
$PCH: possibly delisted; no timezone found
$APTX: possibly delisted; no timezone found
$MODG: possibly delisted; no timezone found
$ATTO: possibly delisted; no timezone found
$CCXI: possibly delisted; no price data found  (1d 2017-01-01 -> 2024-01-01) (Yahoo error = "Data doesn't exist for startDate = 1483246800, endDate = 1704085200")
$OLO: possibly delisted; no timezone found
$PARA: possibly delisted; no timezone found

9 Failed downloads:
['DISC.A', 'TFFP', 'PCH', 'APTX', 'MODG', 'ATTO', 'OLO', 'PARA']: possibly delisted; no timezone found
['CCXI']: possibly delisted; no price data found  (1d 2017-01-01 -> 2024-01-01) (Yahoo error = "Data doesn't exist for startDate = 1483246800, endDate = 1704085200")


  Batch 6/58: fetched 50 tickers, 68502 price rows


$GLYC: possibly delisted; no timezone found
$VRS: possibly delisted; no timezone found
$RDS.A: possibly delisted; no timezone found
$K: possibly delisted; no timezone found
$LHDX: possibly delisted; no timezone found
$ALTR: possibly delisted; no timezone found
$RETA: possibly delisted; no timezone found
$UFS: possibly delisted; no timezone found
$PRFT: possibly delisted; no timezone found
$IGT: possibly delisted; no timezone found
$VRNT: possibly delisted; no price data found  (1d 2017-01-01 -> 2024-01-01)
$IEA: possibly delisted; no timezone found

12 Failed downloads:
['GLYC', 'VRS', 'RDS.A', 'K', 'LHDX', 'ALTR', 'RETA', 'UFS', 'PRFT', 'IGT', 'IEA']: possibly delisted; no timezone found
['VRNT']: possibly delisted; no price data found  (1d 2017-01-01 -> 2024-01-01)


  Batch 7/58: fetched 50 tickers, 65046 price rows


$ONTF: possibly delisted; no timezone found
$IDSY: possibly delisted; no timezone found
$TPX: possibly delisted; no timezone found
$FCAU: possibly delisted; no timezone found
$BEST: possibly delisted; no timezone found
$TWOU: possibly delisted; no timezone found
$DFS: possibly delisted; no timezone found
$X: possibly delisted; no timezone found
$RAIN: possibly delisted; no price data found  (1d 2017-01-01 -> 2024-01-01) (Yahoo error = "Data doesn't exist for startDate = 1483246800, endDate = 1704085200")

9 Failed downloads:
['ONTF', 'IDSY', 'TPX', 'FCAU', 'BEST', 'TWOU', 'DFS', 'X']: possibly delisted; no timezone found
['RAIN']: possibly delisted; no price data found  (1d 2017-01-01 -> 2024-01-01) (Yahoo error = "Data doesn't exist for startDate = 1483246800, endDate = 1704085200")


  Batch 8/58: fetched 50 tickers, 67952 price rows


$EQC: possibly delisted; no timezone found
$SJW: possibly delisted; no timezone found
$SFT: possibly delisted; no timezone found
$WKME: possibly delisted; no timezone found
$YY: possibly delisted; no timezone found
$RTN: possibly delisted; no timezone found
$BKI: possibly delisted; no timezone found
$BKCC: possibly delisted; no timezone found

8 Failed downloads:
['EQC', 'SJW', 'SFT', 'WKME', 'YY', 'RTN', 'BKI', 'BKCC']: possibly delisted; no timezone found


  Batch 9/58: fetched 50 tickers, 70502 price rows


$STON: possibly delisted; no timezone found
$REGI: possibly delisted; no timezone found
$VVNT: possibly delisted; no timezone found
$ABTX: possibly delisted; no timezone found
$HA: possibly delisted; no timezone found
$AFYA): possibly delisted; no timezone found
$HZNP: possibly delisted; no timezone found
$CPSI: possibly delisted; no timezone found
$IPG: possibly delisted; no timezone found
$LPI: possibly delisted; no timezone found
$GPS: possibly delisted; no timezone found
$VOXX: possibly delisted; no timezone found
$AZPN: possibly delisted; no timezone found

13 Failed downloads:
['STON', 'REGI', 'VVNT', 'ABTX', 'HA', 'AFYA)', 'HZNP', 'CPSI', 'IPG', 'LPI', 'GPS', 'VOXX', 'AZPN']: possibly delisted; no timezone found


  Batch 10/58: fetched 50 tickers, 61857 price rows


$NTCO: possibly delisted; no timezone found
$TPRE: possibly delisted; no timezone found
$HMSY: possibly delisted; no timezone found
$AINV: possibly delisted; no timezone found
$NEWR: possibly delisted; no timezone found
$TWNK: possibly delisted; no timezone found
$CIR: possibly delisted; no timezone found
$ALE: possibly delisted; no timezone found
$PGTI: possibly delisted; no timezone found
$KSU: possibly delisted; no timezone found
$VVI: possibly delisted; no timezone found
$BSIG: possibly delisted; no timezone found
$BIG: possibly delisted; no timezone found
$TDCX: possibly delisted; no timezone found
$BGCP: possibly delisted; no timezone found
$CAMP: possibly delisted; no price data found  (1d 2017-01-01 -> 2024-01-01) (Yahoo error = "Data doesn't exist for startDate = 1483246800, endDate = 1704085200")
$FTCH: possibly delisted; no timezone found
$AMBC: possibly delisted; no timezone found
$MIME: possibly delisted; no timezone found

19 Failed downloads:
['NTCO', 'TPRE', 'HMSY', 'AI

  Batch 11/58: fetched 50 tickers, 50814 price rows


$WETF: possibly delisted; no timezone found
$HEAR: possibly delisted; no timezone found
$NLS: possibly delisted; no timezone found
$VNE: possibly delisted; no timezone found
$CMRE): possibly delisted; no timezone found
$MNTV: possibly delisted; no timezone found
$SMTS: possibly delisted; no timezone found
$OCSI: possibly delisted; no timezone found
$GCP: possibly delisted; no timezone found
$GPL: possibly delisted; no timezone found
$SJI: possibly delisted; no timezone found
$ESTA): possibly delisted; no timezone found
$MFGP: possibly delisted; no timezone found
$VRAY: possibly delisted; no timezone found
$ARCE: possibly delisted; no timezone found

15 Failed downloads:
['WETF', 'HEAR', 'NLS', 'VNE', 'CMRE)', 'MNTV', 'SMTS', 'OCSI', 'GCP', 'GPL', 'SJI', 'ESTA)', 'MFGP', 'VRAY', 'ARCE']: possibly delisted; no timezone found


  Batch 12/58: fetched 50 tickers, 59613 price rows


$OTRK: possibly delisted; no price data found  (1d 2017-01-01 -> 2024-01-01) (Yahoo error = "Data doesn't exist for startDate = 1483246800, endDate = 1704085200")
$SPNS: possibly delisted; no timezone found
$VSTO: possibly delisted; no timezone found
$WW: possibly delisted; no price data found  (1d 2017-01-01 -> 2024-01-01) (Yahoo error = "Data doesn't exist for startDate = 1483246800, endDate = 1704085200")
$STER: possibly delisted; no timezone found
$GHL: possibly delisted; no timezone found
$TSE: possibly delisted; no timezone found
$RAD: possibly delisted; no timezone found
$DRNA: possibly delisted; no timezone found
$FUV: possibly delisted; no timezone found
$FLXN: possibly delisted; no price data found  (1d 2017-01-01 -> 2024-01-01) (Yahoo error = "Data doesn't exist for startDate = 1483246800, endDate = 1704085200")

11 Failed downloads:
['OTRK', 'WW', 'FLXN']: possibly delisted; no price data found  (1d 2017-01-01 -> 2024-01-01) (Yahoo error = "Data doesn't exist for startDate 

  Batch 13/58: fetched 50 tickers, 66852 price rows


$CVET: possibly delisted; no timezone found
$MYOK: possibly delisted; no timezone found
$CNSL: possibly delisted; no timezone found
$XM: possibly delisted; no timezone found
$TWTR: possibly delisted; no timezone found
$DSKE: possibly delisted; no timezone found
$UROV: possibly delisted; no timezone found
$CEIX: possibly delisted; no timezone found
$EPZM: possibly delisted; no timezone found
$CDK: possibly delisted; no timezone found

10 Failed downloads:
['CVET', 'MYOK', 'CNSL', 'XM', 'TWTR', 'DSKE', 'UROV', 'CEIX', 'EPZM', 'CDK']: possibly delisted; no timezone found


  Batch 14/58: fetched 50 tickers, 67857 price rows


$NKLA: possibly delisted; no timezone found
$CSSE: possibly delisted; no timezone found
$AZUL: possibly delisted; no price data found  (1d 2017-01-01 -> 2024-01-01) (Yahoo error = "Data doesn't exist for startDate = 1483246800, endDate = 1704085200")
$AQUA: possibly delisted; no timezone found
$SOVO: possibly delisted; no timezone found
$ACCD: possibly delisted; no timezone found
$EVBG: possibly delisted; no timezone found
$MESA: possibly delisted; no timezone found
$FARO: possibly delisted; no timezone found
$NVTA: possibly delisted; no timezone found
$GBT: possibly delisted; no timezone found

11 Failed downloads:
['NKLA', 'CSSE', 'AQUA', 'SOVO', 'ACCD', 'EVBG', 'MESA', 'FARO', 'NVTA', 'GBT']: possibly delisted; no timezone found
['AZUL']: possibly delisted; no price data found  (1d 2017-01-01 -> 2024-01-01) (Yahoo error = "Data doesn't exist for startDate = 1483246800, endDate = 1704085200")


  Batch 15/58: fetched 50 tickers, 63473 price rows


$CRY: possibly delisted; no price data found  (1d 2017-01-01 -> 2024-01-01) (Yahoo error = "Data doesn't exist for startDate = 1483246800, endDate = 1704085200")
$ERF: possibly delisted; no timezone found
$ONDK: possibly delisted; no timezone found
$HRC: possibly delisted; no timezone found
$EURN: possibly delisted; no timezone found
$DCT: possibly delisted; no timezone found
$RTLR: possibly delisted; no timezone found
$GLT: possibly delisted; no timezone found
$CEQP: possibly delisted; no timezone found
$FBHS: possibly delisted; no timezone found
$ETM: possibly delisted; no timezone found
$PFC: possibly delisted; no timezone found

12 Failed downloads:
['CRY']: possibly delisted; no price data found  (1d 2017-01-01 -> 2024-01-01) (Yahoo error = "Data doesn't exist for startDate = 1483246800, endDate = 1704085200")
['ERF', 'ONDK', 'HRC', 'EURN', 'DCT', 'RTLR', 'GLT', 'CEQP', 'FBHS', 'ETM', 'PFC']: possibly delisted; no timezone found


  Batch 16/58: fetched 50 tickers, 63827 price rows


$BIGC: possibly delisted; no timezone found
$RADA: possibly delisted; no timezone found
$SUMO: possibly delisted; no timezone found
$DNAY: possibly delisted; no timezone found
$PRVB: possibly delisted; no timezone found
$OSTK: possibly delisted; no timezone found
$GWGH): possibly delisted; no timezone found
$HNGR: possibly delisted; no timezone found

8 Failed downloads:
['BIGC', 'RADA', 'SUMO', 'DNAY', 'PRVB', 'OSTK', 'GWGH)', 'HNGR']: possibly delisted; no timezone found


  Batch 17/58: fetched 50 tickers, 69227 price rows


$HIBB: possibly delisted; no timezone found
$DCPH: possibly delisted; no timezone found
$CVIA: possibly delisted; no timezone found
$RCII: possibly delisted; no timezone found
$VGR: possibly delisted; no timezone found

5 Failed downloads:
['HIBB', 'DCPH', 'CVIA', 'RCII', 'VGR']: possibly delisted; no timezone found


  Batch 18/58: fetched 50 tickers, 71815 price rows


$JE: possibly delisted; no timezone found
$JWN: possibly delisted; no timezone found
$GOL: possibly delisted; no timezone found
$BPMC: possibly delisted; no timezone found
$CNHI: possibly delisted; no timezone found
$TGH: possibly delisted; no timezone found
$AJX: possibly delisted; no timezone found
$SAIL: possibly delisted; no price data found  (1d 2017-01-01 -> 2024-01-01) (Yahoo error = "Data doesn't exist for startDate = 1483246800, endDate = 1704085200")

8 Failed downloads:
['JE', 'JWN', 'GOL', 'BPMC', 'CNHI', 'TGH', 'AJX']: possibly delisted; no timezone found
['SAIL']: possibly delisted; no price data found  (1d 2017-01-01 -> 2024-01-01) (Yahoo error = "Data doesn't exist for startDate = 1483246800, endDate = 1704085200")


  Batch 19/58: fetched 50 tickers, 70459 price rows


$KAMN: possibly delisted; no timezone found
$FRC: possibly delisted; no timezone found
$JOAN: possibly delisted; no timezone found
$PRTY: possibly delisted; no timezone found
$LBRD.A: possibly delisted; no timezone found
$CS: possibly delisted; no timezone found
$VMW: possibly delisted; no timezone found
$NYMT: possibly delisted; no timezone found
$NATI: possibly delisted; no timezone found
$SHYF: possibly delisted; no timezone found
$MDP: possibly delisted; no timezone found

11 Failed downloads:
['KAMN', 'FRC', 'JOAN', 'PRTY', 'LBRD.A', 'CS', 'VMW', 'NYMT', 'NATI', 'SHYF', 'MDP']: possibly delisted; no timezone found


  Batch 20/58: fetched 50 tickers, 64549 price rows


$MTOR: possibly delisted; no timezone found
$BALY: possibly delisted; no price data found  (1d 2017-01-01 -> 2024-01-01) (Yahoo error = "Data doesn't exist for startDate = 1483246800, endDate = 1704085200")
$AUY: possibly delisted; no timezone found
$AGS: possibly delisted; no timezone found
$NYCB: possibly delisted; no timezone found
$ABMD: possibly delisted; no timezone found
$ZI: possibly delisted; no timezone found
$LGF-A: possibly delisted; no timezone found
$GPP: possibly delisted; no timezone found
$OYST: possibly delisted; no timezone found
$GES: possibly delisted; no timezone found
$ZNGA: possibly delisted; no timezone found
$EVRI: possibly delisted; no timezone found

13 Failed downloads:
['MTOR', 'AUY', 'AGS', 'NYCB', 'ABMD', 'ZI', 'LGF-A', 'GPP', 'OYST', 'GES', 'ZNGA', 'EVRI']: possibly delisted; no timezone found
['BALY']: possibly delisted; no price data found  (1d 2017-01-01 -> 2024-01-01) (Yahoo error = "Data doesn't exist for startDate = 1483246800, endDate = 170408520

  Batch 21/58: fetched 50 tickers, 62973 price rows


$IMGN: possibly delisted; no timezone found
$PXD: possibly delisted; no timezone found
$TRQ: possibly delisted; no timezone found
$REPH: possibly delisted; no timezone found
$USM: possibly delisted; no timezone found
$PRTK: possibly delisted; no timezone found
$GLIBA: possibly delisted; no price data found  (1d 2017-01-01 -> 2024-01-01) (Yahoo error = "Data doesn't exist for startDate = 1483246800, endDate = 1704085200")
$NFH: possibly delisted; no timezone found
$SCU: possibly delisted; no timezone found
$ITCI: possibly delisted; no timezone found
$MMP: possibly delisted; no timezone found
$ABB: possibly delisted; no timezone found
$ZEN: possibly delisted; no timezone found

13 Failed downloads:
['IMGN', 'PXD', 'TRQ', 'REPH', 'USM', 'PRTK', 'NFH', 'SCU', 'ITCI', 'MMP', 'ABB', 'ZEN']: possibly delisted; no timezone found
['GLIBA']: possibly delisted; no price data found  (1d 2017-01-01 -> 2024-01-01) (Yahoo error = "Data doesn't exist for startDate = 1483246800, endDate = 1704085200")


  Batch 22/58: fetched 50 tickers, 61991 price rows


$AVYA: possibly delisted; no timezone found
$BBU: possibly delisted; no timezone found
$TRUE: possibly delisted; no timezone found
$SNV: possibly delisted; no timezone found
$EGLE: possibly delisted; no price data found  (1d 2017-01-01 -> 2024-01-01) (Yahoo error = "Data doesn't exist for startDate = 1483246800, endDate = 1704085200")
$HT: possibly delisted; no timezone found
$MRLN: possibly delisted; no price data found  (1d 2017-01-01 -> 2024-01-01) (Yahoo error = "Data doesn't exist for startDate = 1483246800, endDate = 1704085200")
$ECHO: possibly delisted; no timezone found
$TUP: possibly delisted; no timezone found
$AXL: possibly delisted; no timezone found
$BERY: possibly delisted; no timezone found
$OFC: possibly delisted; no timezone found
$SCWX: possibly delisted; no timezone found
$EXAS: possibly delisted; no timezone found
$SKX: possibly delisted; no timezone found
$RDUS: possibly delisted; no timezone found

16 Failed downloads:
['AVYA', 'BBU', 'TRUE', 'SNV', 'HT', 'ECHO',

  Batch 23/58: fetched 50 tickers, 57539 price rows


$WOLF: possibly delisted; no price data found  (1d 2017-01-01 -> 2024-01-01) (Yahoo error = "Data doesn't exist for startDate = 1483246800, endDate = 1704085200")
$NXGN: possibly delisted; no timezone found
$SLCA: possibly delisted; no timezone found
$ENLC: possibly delisted; no timezone found
$BRG: possibly delisted; no timezone found
$HOLX: possibly delisted; no timezone found
$ATUS: possibly delisted; no timezone found

7 Failed downloads:
['WOLF']: possibly delisted; no price data found  (1d 2017-01-01 -> 2024-01-01) (Yahoo error = "Data doesn't exist for startDate = 1483246800, endDate = 1704085200")
['NXGN', 'SLCA', 'ENLC', 'BRG', 'HOLX', 'ATUS']: possibly delisted; no timezone found


  Batch 24/58: fetched 50 tickers, 72868 price rows


$CNTG: possibly delisted; no timezone found
$VIAO: possibly delisted; no timezone found
$SRT: possibly delisted; no timezone found
$ORCC: possibly delisted; no timezone found
$AZEK: possibly delisted; no timezone found
$ARNA: possibly delisted; no timezone found
$TSU: possibly delisted; no timezone found
$GMDA: possibly delisted; no timezone found
$INFN: possibly delisted; no timezone found
$PSB: possibly delisted; no timezone found
$MDC: possibly delisted; no timezone found
$RRD: possibly delisted; no timezone found
$TEF: possibly delisted; no timezone found
$SDC: possibly delisted; no timezone found

14 Failed downloads:
['CNTG', 'VIAO', 'SRT', 'ORCC', 'AZEK', 'ARNA', 'TSU', 'GMDA', 'INFN', 'PSB', 'MDC', 'RRD', 'TEF', 'SDC']: possibly delisted; no timezone found


  Batch 25/58: fetched 50 tickers, 59855 price rows


$HEES: possibly delisted; no timezone found
$ANSS: possibly delisted; no timezone found
$HTA: possibly delisted; no timezone found
$CDAY: possibly delisted; no timezone found
$MRO: possibly delisted; no timezone found
$ETRN: possibly delisted; no timezone found
$AXNX: possibly delisted; no timezone found
$CYBR: possibly delisted; no timezone found
$AMSWA: possibly delisted; no timezone found

9 Failed downloads:
['HEES', 'ANSS', 'HTA', 'CDAY', 'MRO', 'ETRN', 'AXNX', 'CYBR', 'AMSWA']: possibly delisted; no timezone found


  Batch 26/58: fetched 50 tickers, 69462 price rows


$SPPI: possibly delisted; no timezone found
$TRMR: possibly delisted; no timezone found
$AHH: possibly delisted; no timezone found
$ISEE: possibly delisted; no timezone found
$SMAR: possibly delisted; no timezone found
$IRBT: possibly delisted; no timezone found
$RAAS: possibly delisted; no timezone found
$MXIM: possibly delisted; no timezone found
$BDSI: possibly delisted; no timezone found
$AVID: possibly delisted; no timezone found

10 Failed downloads:
['SPPI', 'TRMR', 'AHH', 'ISEE', 'SMAR', 'IRBT', 'RAAS', 'MXIM', 'BDSI', 'AVID']: possibly delisted; no timezone found


  Batch 27/58: fetched 50 tickers, 66043 price rows


$TMST: possibly delisted; no timezone found
$SBT: possibly delisted; no timezone found
$FGEN: possibly delisted; no timezone found
$RCM: possibly delisted; no timezone found
$SCHN: possibly delisted; no timezone found
$GMS: possibly delisted; no timezone found
$SWAV: possibly delisted; no timezone found
$ERJ: possibly delisted; no timezone found
$GCI: possibly delisted; no timezone found
$ZLND.Y: possibly delisted; no timezone found
$ENV: possibly delisted; no timezone found
$BECN: possibly delisted; no timezone found

12 Failed downloads:
['TMST', 'SBT', 'FGEN', 'RCM', 'SCHN', 'GMS', 'SWAV', 'ERJ', 'GCI', 'ZLND.Y', 'ENV', 'BECN']: possibly delisted; no timezone found


  Batch 28/58: fetched 50 tickers, 63481 price rows


$HFC: possibly delisted; no timezone found
$OTIC: possibly delisted; no timezone found
$CUTR: possibly delisted; no timezone found
$CFLT: possibly delisted; no timezone found
$EXTN: possibly delisted; no timezone found
$VIAB: possibly delisted; no timezone found
$SPTN: possibly delisted; no timezone found
$CPLG: possibly delisted; no timezone found
$CMA: possibly delisted; no timezone found
$INT: possibly delisted; no timezone found

10 Failed downloads:
['HFC', 'OTIC', 'CUTR', 'CFLT', 'EXTN', 'VIAB', 'SPTN', 'CPLG', 'CMA', 'INT']: possibly delisted; no timezone found


  Batch 29/58: fetched 50 tickers, 65234 price rows


$APTV): possibly delisted; no timezone found
$DVAX: possibly delisted; no timezone found
$HHC: possibly delisted; no timezone found
$ZEAL: possibly delisted; no timezone found
$ATAX: possibly delisted; no timezone found
$STOR: possibly delisted; no timezone found
$VSTA: possibly delisted; no timezone found
$MMC: possibly delisted; no timezone found
$COOP: possibly delisted; no timezone found
$LTRPA: possibly delisted; no timezone found
$QRTEA: possibly delisted; no timezone found
$BRY: possibly delisted; no timezone found
$AXE: possibly delisted; no timezone found

13 Failed downloads:
['APTV)', 'DVAX', 'HHC', 'ZEAL', 'ATAX', 'STOR', 'VSTA', 'MMC', 'COOP', 'LTRPA', 'QRTEA', 'BRY', 'AXE']: possibly delisted; no timezone found


  Batch 30/58: fetched 50 tickers, 64182 price rows


$JAMF: possibly delisted; no timezone found
$HUD: possibly delisted; no timezone found
$RDFN: possibly delisted; no timezone found
$RUTH: possibly delisted; no timezone found
$SAGE: possibly delisted; no timezone found
$VRM: possibly delisted; no price data found  (1d 2017-01-01 -> 2024-01-01) (Yahoo error = "Data doesn't exist for startDate = 1483246800, endDate = 1704085200")

23 Failed downloads:
['JAMF', 'HUD', 'RDFN', 'RUTH', 'SAGE']: possibly delisted; no timezone found
['VRM']: possibly delisted; no price data found  (1d 2017-01-01 -> 2024-01-01) (Yahoo error = "Data doesn't exist for startDate = 1483246800, endDate = 1704085200")
['AERI', 'JBT', 'ANDE', 'OB', 'CEVA', 'SUN', 'YUM', 'BDX', 'BBDC', 'ADP', 'IRT', 'NATR', 'LFST', 'CONN', 'KMPR', 'BMO', 'AMC']: YFRateLimitError('Too Many Requests. Rate limited. Try after a while.')


  Batch 31/58: fetched 50 tickers, 44351 price rows



50 Failed downloads:
['ALIM', 'OMI', 'ZENV', 'ACB', 'FLXS', 'INMD', 'TPR', 'AGEN', 'RGP', 'WLK', 'PRCT', 'ELAN', 'CMRX', 'CRH', 'WING', 'PLXS', 'MITK', 'ODFL', 'DOC', 'CRNT', 'FTCI', 'SLGN', 'DXC', 'EXPR', 'WIRE', 'ADC', 'CWAN', 'CW', 'AKAM', 'TERP', 'DMS', 'VEEV', 'NTRS', 'MS', 'LEVI', 'QLYS', 'CAMT', 'MTN', 'SSTK', 'BEDU', 'YOU', 'AOS', 'AIV', 'KIRK', 'CLR', 'NLTX', 'SPLK', 'PRU', 'KTOS', 'KBH']: YFRateLimitError('Too Many Requests. Rate limited. Try after a while.')


  Batch 32/58: fetched 50 tickers, 0 price rows



41 Failed downloads:
['CBD', 'HUM', 'MITT', 'TECK', 'BZ', 'GSL', 'WEC', 'XOM', 'FDX', 'ATO', 'QGEN', 'HAIN', 'MTD', 'PII', 'HUBG', 'IEX', 'SEE', 'CRM', 'HLNE', 'YQ', 'CCAP', 'ABUS', 'TEVA', 'CHX', 'GGB', 'W', 'AVAV', 'SIGI', 'MAR', 'BELFB', 'KSS', 'DAN', 'SLB', 'SPWR', 'STAR', 'JKHY', 'HY', 'THRM', 'SGH', 'SPGI', 'NMFC']: YFRateLimitError('Too Many Requests. Rate limited. Try after a while.')


  Batch 33/58: fetched 50 tickers, 14759 price rows



49 Failed downloads:
['CPLP', 'CHMA', 'PLYM', 'TOL', 'LUNG', 'ENVA', 'UNF', 'CHH', 'GNL', 'AHT', 'SWI', 'LPSN', 'UXIN', 'BYD', 'LI', 'CUBI', 'PING', 'PNW', 'EAT', 'SAP', 'HBI', 'EYE', 'GPN', 'VTR', 'SRDX', 'AQST', 'EPR', 'HOG', 'HSIC', 'USNA', 'EWBC', 'VSAT', 'JW.A', 'OPI', 'ABG', 'AMCX', 'VREX', 'BBVA', 'BRBR', 'CTVA', 'JKS', 'NFG', 'ITI', 'MGY', 'LSI', 'ARR', 'MRK', 'CZR', 'ABCL']: YFRateLimitError('Too Many Requests. Rate limited. Try after a while.')


  Batch 34/58: fetched 50 tickers, 1760 price rows


$HEP: possibly delisted; no timezone found
$ARD: possibly delisted; no timezone found

36 Failed downloads:
['CBAY', 'NCNO', 'SHG', 'IVC', 'INNV', 'NNN', 'AVO', 'TTI', 'PCRX', 'DISH', 'IBEX', 'EXR', 'AMED', 'BXMT', 'SNA', 'BRFS', 'GIII', 'NIU', 'CCMP', 'JNCE', 'CRMT', 'CVBF', 'FFIV', 'QIWI', 'CALA', 'FOCS', 'CSL', 'TGP', 'ADAP', 'FRME', 'AIG', 'SNBR', 'PWFL', 'BILL']: YFRateLimitError('Too Many Requests. Rate limited. Try after a while.')
['HEP', 'ARD']: possibly delisted; no timezone found


  Batch 35/58: fetched 50 tickers, 21924 price rows


$BIO.B: possibly delisted; no price data found  (1d 2017-01-01 -> 2024-01-01)
$ARNC: possibly delisted; no timezone found

46 Failed downloads:
['DSSI', 'CPL', 'AMWD', 'SEM', 'PRAA', 'ELV', 'AFG', 'SVC', 'ECOL', 'TXG', 'ATSG', 'FITB', 'CDLX', 'UFI', 'HTLF', 'KVHI', 'BMA', 'EBR', 'RUSHB', 'MCFE', 'FSV', 'KRT', 'CPNG', 'CSTM', 'UAL', 'GPX', 'CX', 'ZION', 'CHUY', 'CENX', 'ROCK', 'CMCM', 'SUZ', 'GLPG', 'MSFT', 'AIN', 'COMM', 'RJF', 'COLB', 'AMRS', 'KN', 'PAAS', 'ATCO', 'FSS']: YFRateLimitError('Too Many Requests. Rate limited. Try after a while.')
['BIO.B']: possibly delisted; no price data found  (1d 2017-01-01 -> 2024-01-01)
['ARNC']: possibly delisted; no timezone found


  Batch 36/58: fetched 50 tickers, 6161 price rows



48 Failed downloads:
['REVG', 'VIE', 'HMST', 'UTHR', 'INGR', 'HE', 'ADI', 'PHX', 'CELH', 'CHEF', 'KRG', 'RIO', 'TREE', 'FIGS', 'PAGS', 'OVV', 'APTO', 'GHM', 'BHF', 'CERS', 'TRI', 'RPM', 'LKQ', 'HALO', 'GFL', 'ODC', 'PDS', 'CUB', 'CRK', 'MRVI', 'SGC', 'ITGR', 'CP', 'MCRB', 'CTO', 'DISCA', 'OCN', 'BAK', 'RYN', 'SMWB', 'AZTA', 'AVNT', 'HCRS.Q', 'CSX', 'PFBC', 'HZN', 'SNCR', 'ULCC']: YFRateLimitError('Too Many Requests. Rate limited. Try after a while.')


  Batch 37/58: fetched 50 tickers, 3520 price rows



49 Failed downloads:
['CFX', 'POSH', 'TIPT', 'UIS', 'AFYA', 'LAKE', 'CSWC', 'KODK', 'BHC', 'KMT', 'VTRU', 'RYAM', 'TFX', 'MQ', 'AKBA', 'FORR', 'JHX', 'SATS', 'STKL', 'FTI', 'SCOR', 'YELP', 'TPC', 'UVSP', 'MHO', 'SWCH', 'FAF', 'RGEN', 'SMCI', 'UMPQ', 'CYTK', 'BCE', 'INN', 'AVDL', 'BLI', 'JT', 'AGFY', 'HAYW', 'WES', 'TER', 'PWFL)', 'BXP', 'SOPH', 'CMCSA', 'PBA', 'LCUT', 'IBA', 'TEL', 'OPB']: YFRateLimitError('Too Many Requests. Rate limited. Try after a while.')


  Batch 38/58: fetched 50 tickers, 1760 price rows



50 Failed downloads:
['MYTE', 'ADMS', 'EMN', 'ALGT', 'RAMP', 'COR', 'AMH', 'XEL', 'CMD', 'GT', 'OPCH', 'GLOP', 'SFIX', 'FNB', 'RXT', 'TBPH', 'AGO', 'SUPV', 'ATR', 'SRE', 'MEG', 'NWG', 'MPW', 'AXS', 'CNXN', 'LESL', 'XNET', 'CIEN', 'WU', 'SNDR', 'TUSK', 'SMTC', 'LNTH', 'NARI', 'EQT', 'WAB', 'AAIC', 'RMBS', 'GPK', 'PTVE', 'YSG', 'ARGO', 'LTC', 'ROP', 'REDU', 'NH', 'ROAD', 'IFF', 'DYNC)', 'SAIC']: YFRateLimitError('Too Many Requests. Rate limited. Try after a while.')


  Batch 39/58: fetched 50 tickers, 0 price rows



50 Failed downloads:
['YELL', 'CSII', 'GMAB', 'NP', 'MPAA', 'IVZ', 'TS', 'PKG', 'SHSP', 'MTRX', 'GAMB', 'PRDO', 'TWI', 'CWCO', 'HASI', 'NUVA', 'CTXS', 'CGC', 'MGIC', 'RPRX', 'HYFM', 'MAS', 'FIS', 'SFL', 'MSP', 'ACC', 'AMKR', 'KGC', 'KFY', 'CNNE', 'CPRT', 'RELX', 'UPST', 'CSLT', 'ASGN', 'ACRX', 'CXP', 'KOF', 'BNS', 'MXL', 'LNT', 'CRSR', 'OC', 'WUBA', 'WMG', 'FLY', 'LTHM', 'BL', 'FTNT', 'EQH']: YFRateLimitError('Too Many Requests. Rate limited. Try after a while.')


  Batch 40/58: fetched 50 tickers, 0 price rows


$MR: possibly delisted; no timezone found

47 Failed downloads:
['COWN', 'PLYA', 'MWA', 'NGL', 'DEI', 'HEI', 'TTPH', 'VKTX', 'SPSC', 'TGS', 'GGG', 'CNK', 'ADT', 'GSM', 'PNNT', 'FISV', 'MSGM', 'ANGO', 'TM', 'ICAD', 'CNF', 'SOHU', 'WCC', 'KELYA', 'WBT', 'RTL', 'VALN)', 'DAKT', 'GDDY', 'KHC', 'ATRA', 'AY', 'BANR', 'CEL', 'GTE', 'USFD', 'VC', 'BVN)', 'CATY', 'TKC', 'PDFS', 'WRBY', 'DEA', 'DRE', 'MNRO', 'CIO']: YFRateLimitError('Too Many Requests. Rate limited. Try after a while.')
['MR']: possibly delisted; no timezone found


  Batch 41/58: fetched 50 tickers, 4149 price rows



50 Failed downloads:
['ATHX', 'SEAS', 'DD', 'CPF', 'RLI', 'AWR', 'CWST', 'PLTK', 'GAN', 'CDE', 'AWH', 'SLF', 'KRA', 'RVNC', 'FRT', 'DNUT', 'GRBK', 'MYE', 'ALEX', 'KUKE', 'EDIT', 'POWI', 'FLWS', 'DNOW', 'FOE', 'AMCR', 'AVIR', 'SWIM', 'KL', 'ATNX', 'ECPG', 'ARLO', 'FPH', 'SLQT', 'CMI', 'SUPN', 'IDN', 'NVRO', 'GORO', 'NVST', 'LHX', 'CTSO', 'MNDY', 'AMK', 'YMM', 'FELE', 'SMLP', 'ICFI', 'NS', 'KB']: YFRateLimitError('Too Many Requests. Rate limited. Try after a while.')


  Batch 42/58: fetched 50 tickers, 0 price rows



50 Failed downloads:
['GLUU', 'OSH', 'PDCO', 'YRD', 'RWT', 'ORI', 'SAR', 'MERC', 'STC', 'ROOT', 'ARCH', 'FSP', 'FTDR', 'NWL', 'XPOF', 'CULP', 'IHRT', 'LPRO', 'PCAR', 'XPER', 'BBCP', 'SGHT', 'SNPS', 'INFY', 'INSM', 'SIR)', 'IP', 'BSY', 'SWIR', 'AVXL', 'HLI', 'ILMN', 'ANH', 'NTAP', 'KLIC', 'CLW', 'TSCO', 'FWRD', 'AX.DL', 'CVAC', 'ACTG', 'UGP', 'WCN', 'POST', 'RDNT', 'SAMG', 'DOOO', 'WRK', 'DOLE', 'LPX']: YFRateLimitError('Too Many Requests. Rate limited. Try after a while.')


  Batch 43/58: fetched 50 tickers, 0 price rows



50 Failed downloads:
['VAPO', 'QTNT', 'BCC', 'ATNI', 'IIIN', 'R', 'HAFC', 'VIOT', 'SAIA', 'AEYE', 'CWK', 'INSP', 'RGNX', 'MUSA', 'INSW', 'CNTY', 'MATW', 'HWC', 'DZSI', 'SIEN', 'SPT', 'CHRW', 'RNST', 'WMB', 'WSR', 'TCMD', 'VRTS', 'BGS', 'CERT', 'M', 'FMS', 'ALX', 'UNVR', 'KIM', 'BRKL', 'GTHX', 'TRTN', 'MAA', 'WBK', 'ONEW', 'FBK', 'CCOI', 'PK', 'AUB', 'AEGN', 'MOR', 'DXPE', 'FBP', 'VICR', 'LMNR']: YFRateLimitError('Too Many Requests. Rate limited. Try after a while.')


  Batch 44/58: fetched 50 tickers, 0 price rows



49 Failed downloads:
['HI', 'ZYXI', 'CVLT', 'IRWD', 'CPA', 'PFS', 'VG', 'MGI', 'WWD', 'RPD', 'SITE', 'MKSI', 'QNST', 'TA', 'PNTG', 'SHOO', 'AM', 'CPRI', 'TRHC', 'NVMI', 'WD', 'WH', 'SHAK', 'IAA', 'JHG', 'AVA', 'SR', 'SXI', 'SWX', 'BBD', 'SGMO', 'PEB', 'NI', 'BXS', 'NSP', 'WERN', 'GIB', 'EXC', 'PYCR', 'DIOD', 'UGI', 'BCEI', 'HP', 'HCM', 'WY', 'WIT', 'CMCO', 'EPRT', 'DGII']: YFRateLimitError('Too Many Requests. Rate limited. Try after a while.')


  Batch 45/58: fetched 50 tickers, 1704 price rows



50 Failed downloads:
['SPR', 'OMP', 'STXB', 'DENN', 'BV', 'ASB', 'ALG', 'LANC', 'LIVN', 'PPC', 'UVE', 'BKH', 'LU', 'CHMI', 'EAR', 'AGRX', 'GWB', 'VAC', 'MFC', 'MTLS', 'GOLF', 'ALBO', 'UIHC', 'APPF', 'DX', 'DESP', 'INGN', 'UCBI', 'SFNC', 'ITUB', 'CSWI', 'GPC', 'WLTW', 'CONE', 'AGRO', 'IRTC', 'AKR', 'REG', 'FRGI', 'AEP', 'ANIK', 'SMPL', 'ACHC', 'GSBC', 'VLY', 'IIIV', 'PLMR', 'OMF', 'PPD', 'USAC']: YFRateLimitError('Too Many Requests. Rate limited. Try after a while.')


  Batch 46/58: fetched 50 tickers, 0 price rows



50 Failed downloads:
['FANH', 'WLL', 'RESN', 'OSIS', 'HVT', 'MMSI', 'GWRE', 'ABCB', 'SUM', 'TTGT', 'POR', 'RHI', 'THS', 'NR', 'OFG', 'PUMP', 'RNR', 'FLS', 'SHLX', 'AMPH', 'FDUS', 'FLT', 'YUMC', 'BANC', 'HCI', 'JBHT', 'AGR', 'AMN', 'PBH', 'CIVB', 'TNC', 'ASND', 'KREF', 'FIX', 'UFCS', 'DTE', 'COLL', 'CUZ', 'HIG', 'BAH', 'FULT', 'NEXA', 'ASPS', 'RSG', 'FTAI', 'MHK', 'EQR', 'VBTX', 'CAL', 'STRA']: YFRateLimitError('Too Many Requests. Rate limited. Try after a while.')


  Batch 47/58: fetched 50 tickers, 0 price rows



47 Failed downloads:
['PEAK', 'RBC', 'RPT', 'BSM', 'FORM', 'ITT', 'KURA', 'ONB', 'TV', 'IART', 'CSPR', 'EB', 'PSA', 'TTMI', 'FCF', 'APH', 'AZRE', 'UMBF', 'AAT', 'EVRG', 'FUL', 'OGS', 'ARW', 'API', 'CHNG', 'PSXP', 'CVI', 'CVCO', 'BPOP', 'PTCT', 'EVOP', 'ZIXI', 'HES', 'AVNS', 'CCR', 'LPG', 'GIL', 'INVH', 'ENTA', 'TDY', 'VNDA', 'CNQ', 'THG', 'TMHC', 'FMC', 'SHO', 'CHT']: YFRateLimitError('Too Many Requests. Rate limited. Try after a while.')


  Batch 48/58: fetched 50 tickers, 5280 price rows


$SRC: possibly delisted; no timezone found

43 Failed downloads:
['HSII', 'TLS', 'ARES', 'CTMX', 'EFSC', 'CLLS', 'ACA', 'SLN', 'AVY', 'ODP', 'CALX', 'FR', 'CDXC', 'XLRN', 'AME', 'ROCC', 'WPX', 'BOKF', 'GEN', 'TALO', 'NMRK', 'AGI', 'FLO', 'ROIC', 'MET', 'TAC', 'TRS', 'AAN', 'AIZ', 'NBEV', 'SKY', 'J', 'ELP', 'ZIM', 'TSLX', 'CNCE', 'CRL', 'PH', 'EVA', 'PRA', 'SASR', 'HPP']: YFRateLimitError('Too Many Requests. Rate limited. Try after a while.')
['SRC']: possibly delisted; no timezone found


  Batch 49/58: fetched 50 tickers, 12200 price rows



40 Failed downloads:
['SWN', 'MOG.A', 'PROG', 'EPAY', 'PAHC', 'BLFS', 'HCCI', 'LNDC', 'OFIX', 'CTRE', 'IDEX', 'NGMS', 'WOOF', 'NXRT', 'CR', 'AAON', 'OSCR', 'DY', 'ANIP', 'XNCR', 'CNMD', 'MGP', 'ROLL', 'OXLC', 'WTRG', 'TEN', 'CDW', 'IBP', 'AEE', 'AFRM', 'IPAR', 'CVGI', 'RMAX', 'SSNC', 'CCJ', 'LDOS', 'EIX', 'LEG', 'THRY', 'SEIC']: YFRateLimitError('Too Many Requests. Rate limited. Try after a while.')


  Batch 50/58: fetched 50 tickers, 17600 price rows


$STL: possibly delisted; no timezone found

45 Failed downloads:
['LIVX', 'EFC', 'ESNT', 'PEGA', 'SPXC', 'CBU', 'TCPC', 'SYNA', 'NICE', 'IBTX', 'OR', 'DUO', 'HOUS', 'HMN', 'PNFP', 'IMMR', 'OSK', 'PKI', 'NHI', 'AVTR', 'FLOW', 'LYG', 'ZBH', 'NBHC', 'CG', 'RES', 'ARI', 'BLKB', 'B', 'LCI', 'HMTV', 'THC', 'PGEN', 'REZI', 'NLSN', 'ADTN', 'EXPO', 'UHS', 'WSFS', 'ASPU', 'REXR', 'EPC', 'SAND', 'MMI']: YFRateLimitError('Too Many Requests. Rate limited. Try after a while.')
['STL']: possibly delisted; no timezone found


  Batch 51/58: fetched 50 tickers, 8800 price rows



49 Failed downloads:
['SYX', 'AXU', 'BKD', 'OMAB', 'IRDM', 'VCTR', 'HWM', 'ABC', 'NBTB', 'UVV', 'CEPU', 'ATGE', 'PB', 'SAH', 'FHI', 'NTUS', 'MANT', 'KDP', 'SID', 'SYNH', 'EGP', 'PDCE', 'ATEC', 'NVEC', 'EFX', 'CCS', 'NEPT', 'MNRL', 'BSAC', 'VCRA', 'FRBA', 'SBCF', 'BLD', 'CPK', 'CAC', 'EHC', 'HSC', 'PRMW', 'DBD', 'UDR', 'AEL', 'NMR', 'RE', 'TVTY', 'CDEV', 'AEG', 'AVLR', 'PINC', 'KKR']: YFRateLimitError('Too Many Requests. Rate limited. Try after a while.')


  Batch 52/58: fetched 50 tickers, 1760 price rows


$BHLB: possibly delisted; no timezone found

47 Failed downloads:
['BPMP', 'EC', 'TYL', 'OUT', 'WRE', 'EMR', 'ADMA', 'FICO', 'ADUS', 'SAN', 'ETR', 'SAVE', 'GNE', 'DSPG', 'SGRY', 'ALC', 'FND', 'APP', 'DNB', 'EVR', 'CVE', 'LNW', 'TNL', 'CTLT', 'AMSF', 'OLN', 'UMC', 'MD', 'CO', 'NEOG', 'SRCL', 'IAG', 'APTV', 'INDB', 'XEC', 'IDA', 'ES', 'ASX', 'BE', 'RGR', 'VRTV', 'AIRC', 'VIVO', 'JNPR', 'ROL', 'HAYN']: YFRateLimitError('Too Many Requests. Rate limited. Try after a while.')
['BHLB']: possibly delisted; no timezone found


  Batch 53/58: fetched 50 tickers, 5280 price rows



48 Failed downloads:
['HSKA', 'HMPT', 'GP', 'NSIT', 'MATV', 'PZZA', 'ETN', 'GATO', 'PTR', 'PFG', 'AES', 'KT', 'VYNE', 'QMCO', 'VMC', 'DE', 'SI', 'DRQ', 'TSHA', 'EGIO', 'MDRX', 'OCDX', 'GHLD', 'LBRDK', 'RGA', 'FRG', 'IMAB', 'DRVN', 'CIG', 'SKYT', 'UNIT', 'BRO', 'BF.B', 'NWS', 'IMV', 'HLF', 'IOVA', 'CERN', 'LL', 'OESX', 'DEN', 'SSL', 'TIXT', 'KNBE', 'MC', 'PJT', 'DCP', 'ADBE']: YFRateLimitError('Too Many Requests. Rate limited. Try after a while.')


  Batch 54/58: fetched 50 tickers, 2949 price rows


$TGI: possibly delisted; no timezone found

44 Failed downloads:
['AKYA', 'VALN', 'NNOX', 'PAX', 'TLIS)', 'MASS', 'PRVA', 'GSX', 'ADV', 'DIBS', 'S', 'PAY', 'PEIX)', 'ERIC', 'NOTE', 'ABOS', 'TPG', 'KLTR', 'EWCZ', 'WEBR', 'BFLY', 'O', 'BLNK', 'EBET', 'ZIMV', 'CAR', 'OMIC', 'PCOR', 'NVAX', 'XMTR', 'SRAD', 'PUBM', 'LZ', 'BVS', 'ZETA', 'OM', 'PLTK)', 'GO', 'FUBO', 'ALTO', 'TUYA', 'EE', 'ESMT']: YFRateLimitError('Too Many Requests. Rate limited. Try after a while.')
['TGI']: possibly delisted; no timezone found


  Batch 55/58: fetched 50 tickers, 6874 price rows



47 Failed downloads:
['TLIS', 'SQSP', 'BLFY', 'AVAH', 'CMPS', 'WKME)', 'FSBC', 'PRO', 'RXST', 'OTLY', 'SNCY', 'CSAN', 'PRG', 'BRLT', 'XPRO', 'ABSI', 'GLBE', 'HLMN)', 'RSKD', 'DUOL', 'DCFC', 'KARO', 'FORG', 'AFCG', 'MCW', 'CEG', 'SHC', 'NEP', 'CENTA', 'TFIN', 'EBC', 'DASH', 'ZIP', 'VTOL)', 'IAS', 'FRSH', 'CRDO', 'BASE', 'PROF', 'EDR', 'SGFY', 'AOMR', 'AGTI', 'PATH', 'STVN', 'HNST', 'APR']: YFRateLimitError('Too Many Requests. Rate limited. Try after a while.')


  Batch 56/58: fetched 50 tickers, 3126 price rows



50 Failed downloads:
['IGIC)', 'DOCS', 'NYXH', 'FLYW', 'BNL', 'EDU', 'ACVA', 'ACAD', 'THRN', 'MCG', 'VTEX', 'COOK', 'COUR', 'TMX', 'PSN', 'SGFY)', 'NPCE', 'HEPS', 'ADN', 'BROS', 'NTRA', 'AGL)', 'TCRT', 'ESTA', 'DH', 'BHG', 'AXAHY', 'VTOL', 'TOST', 'RPID', 'VTRS', 'KW', 'ALKT', 'AKYA)', 'ZY', 'EGHT', 'ALHC', 'QS', 'MLNK', 'WDH', 'GLS', 'AKA', 'AMEH', 'SKLZ', 'PFHC', 'FYBR', 'MPLN', 'PECO', 'TPL', 'SWIM)']: YFRateLimitError('Too Many Requests. Rate limited. Try after a while.')


  Batch 57/58: fetched 50 tickers, 0 price rows



26 Failed downloads:
['POLY', 'MF', 'ADV)', 'NRGV', 'ARE', 'AEVA', 'CRGY', 'AGL', 'BLCO', 'MOLN', 'AFMD', 'CIB)', 'RAIN)', 'FAST', 'MP', 'DDI', 'FSR', 'TIMB', 'CPG', 'BBL', 'BAND', 'LC', 'TSP', 'KRT)', 'STE', 'ALLO']: YFRateLimitError('Too Many Requests. Rate limited. Try after a while.')


  Batch 58/58: fetched 26 tickers, 0 price rows

Combining all price data...

Price data shape: (2124613, 3)
Unique tickers with price data: 1274
Date range: 2017-01-03 00:00:00 to 2023-12-29 00:00:00
Failed tickers: 0

Sample:
        Date ticker      close
0 2017-01-03      A  43.295746
1 2017-01-04      A  43.863842
2 2017-01-05      A  43.342312
3 2017-01-06      A  44.692699
4 2017-01-09      A  44.832378
5 2017-01-10      A  44.795135
6 2017-01-11      A  45.866119
7 2017-01-12      A  45.186287
8 2017-01-13      A  45.344597
9 2017-01-17      A  45.000023

Tickers with no price data (delisted/invalid): 1602
Usable ticker universe: 1274

Saved: Data/stock_prices.csv

Fetching S&P 500 benchmark (^GSPC)...
S&P 500 rows: 1760
Sample:
        Date  sp500_close
0 2017-01-03  2257.830078
1 2017-01-04  2270.750000
2 2017-01-05  2269.000000
3 2017-01-06  2276.979980
4 2017-01-09  2268.899902

Saved: Data/sp500_prices.csv


**Join Transcripts to Price Data**

In [23]:
df = pd.read_csv('Data/data_speakers_parsed.csv')
price_df = pd.read_csv('Data/stock_prices.csv', parse_dates=['Date'])

# ── Ensure earnings_date is datetime ─────────────────────────────────────────
df['earnings_date'] = pd.to_datetime(df['earnings_date'], errors='coerce')
price_df['Date'] = pd.to_datetime(price_df['Date'])

print(f"Transcripts before join: {len(df)}")
print(f"Price rows available:    {len(price_df)}")

# ── Helper: find nearest trading day price for a given ticker + date ──────────
def get_price_on_or_after(ticker_prices, target_date, max_days=5):
    """
    Find closing price on target_date or the next available trading day
    within max_days. Returns NaN if not found.
    """
    for offset in range(max_days + 1):
        lookup_date = target_date + pd.Timedelta(days=offset)
        match = ticker_prices[ticker_prices['Date'] == lookup_date]
        if len(match) > 0:
            return match['close'].iloc[0], offset
    return np.nan, np.nan

# ── Compute forward returns for each transcript ───────────────────────────────
print("\nComputing forward returns for each transcript...")

# Group price data by ticker for faster lookup
price_by_ticker = {
    ticker: group.set_index('Date')['close']
    for ticker, group in price_df.groupby('ticker')
}

results = []
skipped = 0

for idx, row in df.iterrows():
    ticker = row['ticker']
    earn_date = row['earnings_date']

    # Skip if no price data available for this ticker
    if ticker not in price_by_ticker:
        skipped += 1
        continue

    prices = price_by_ticker[ticker]

    try:
        # Get base price: closing price on or just after earnings date
        base_price = None
        for offset in range(6):
            lookup = earn_date + pd.Timedelta(days=offset)
            if lookup in prices.index:
                base_price = prices[lookup]
                break

        if base_price is None or pd.isna(base_price) or base_price == 0:
            skipped += 1
            continue

        # ── Helper: get the Nth trading day after earnings date ───────────────────────
        def get_nth_trading_day_price(prices_series, start_date, n_trading_days):
            """
            Returns the closing price on the Nth available trading day after start_date. 
            """
            future_prices = prices_series[prices_series.index > start_date]
            if len(future_prices) >= n_trading_days:
                return future_prices.iloc[n_trading_days - 1]
            return np.nan

        price_5d  = get_nth_trading_day_price(prices, earn_date, 5)
        price_10d = get_nth_trading_day_price(prices, earn_date, 10)
        price_20d = get_nth_trading_day_price(prices, earn_date, 20)

        # Compute returns
        return_5d  = (price_5d  / base_price - 1) if not pd.isna(price_5d)  else np.nan
        return_10d = (price_10d / base_price - 1) if not pd.isna(price_10d) else np.nan
        return_20d = (price_20d / base_price - 1) if not pd.isna(price_20d) else np.nan

        results.append({
            'idx'       : idx,
            'base_price': base_price,
            'price_5d'  : price_5d,
            'price_10d' : price_10d,
            'price_20d' : price_20d,
            'return_5d' : return_5d,
            'return_10d': return_10d,
            'return_20d': return_20d,
            'label_5d'  : 1 if return_5d  > 0 else 0 if not pd.isna(return_5d)  else np.nan,
            'label_10d' : 1 if return_10d > 0 else 0 if not pd.isna(return_10d) else np.nan,
            'label_20d' : 1 if return_20d > 0 else 0 if not pd.isna(return_20d) else np.nan,
        })

    except Exception as e:
        skipped += 1
        continue

# ── Merge results back into main dataframe ────────────────────────────────────
print(f"Successfully computed returns: {len(results)}")
print(f"Skipped (no price data):       {skipped}")

results_df = pd.DataFrame(results).set_index('idx')
df = df.join(results_df)

# ── Drop rows with no return data ─────────────────────────────────────────────
df_before = len(df)
df_final = df.dropna(subset=['return_5d', 'return_10d', 'return_20d']).copy()
print(f"\nRows before dropping missing returns: {df_before}")
print(f"Rows after  dropping missing returns: {len(df_final)}")
print(f"Dropped: {df_before - len(df_final)}")

# ── Check label distribution ──────────────────────────────────────────────────
print(f"\nLabel distribution (5-day):")
print(df_final['label_5d'].value_counts())
print(f"\nLabel distribution (10-day):")
print(df_final['label_10d'].value_counts())
print(f"\nLabel distribution (20-day):")
print(df_final['label_20d'].value_counts())

# ── Return distribution summary ───────────────────────────────────────────────
print(f"\nReturn summary:")
print(df_final[['return_5d', 'return_10d', 'return_20d']].describe())

# ── Ticker coverage ───────────────────────────────────────────────────────────
print(f"\nFinal usable tickers: {df_final['ticker'].nunique()}")
print(f"Final usable rows:    {len(df_final)}")

# ── Save final cleaned dataset ────────────────────────────────────────────────
if 'exec_text' in df_final.columns:
    df_final['management_text'] = df_final['exec_text']
if 'analyst_text' in df_final.columns:
    df_final['qa_text'] = df_final['analyst_text']

cols_to_save = [
    'ticker', 'earnings_date', 'q', 'earnings_date_is_approx',
    'transcript', 'transcript_clean', 'exec_text', 'analyst_text',
    'speaker_parse_success', 'return_5d', 'return_10d', 'return_20d',
    'label_5d', 'label_10d', 'label_20d'
]

existing_cols = [c for c in cols_to_save if c in df_final.columns]
df_final[existing_cols].to_csv('Data/cleaned_transcripts.csv', index=False)

print(f"\nSaved columns: {existing_cols}")
print("\nSaved: cleaned_transcripts.csv")

Transcripts before join: 18755
Price rows available:    2124613

Computing forward returns for each transcript...
Successfully computed returns: 224
Skipped (no price data):       18531

Rows before dropping missing returns: 18755
Rows after  dropping missing returns: 224
Dropped: 18531

Label distribution (5-day):
label_5d
1.0    126
0.0     98
Name: count, dtype: int64

Label distribution (10-day):
label_10d
0.0    121
1.0    103
Name: count, dtype: int64

Label distribution (20-day):
label_20d
0.0    125
1.0     99
Name: count, dtype: int64

Return summary:
        return_5d  return_10d  return_20d
count  224.000000  224.000000  224.000000
mean     0.003540   -0.008665   -0.018171
std      0.045833    0.074529    0.111643
min     -0.224993   -0.218246   -0.349369
25%     -0.018746   -0.059243   -0.088587
50%      0.005026   -0.007348   -0.009944
75%      0.027083    0.026843    0.045383
max      0.156105    0.310665    0.356239

Final usable tickers: 157
Final usable rows:    224

S

In [24]:
# ── Diagnose fail join ─────────────────────────────────────────

# Check 1: How many transcript tickers are in price_by_ticker?
transcript_tickers = set(df['ticker'].dropna().unique())
price_tickers = set(price_by_ticker.keys())
overlap = transcript_tickers & price_tickers

print(f"Transcript tickers:          {len(transcript_tickers)}")
print(f"Price tickers available:     {len(price_tickers)}")
print(f"Overlap (should match):      {len(overlap)}")

# Check 2: Sample a few tickers that should have matched
sample_tickers = list(overlap)[:5]
for t in sample_tickers:
    mask = df['ticker'] == t
    sample_dates = df[mask]['earnings_date'].head(3)
    prices = price_by_ticker[t]
    print(f"\nTicker: {t}")
    print(f"  Earnings dates: {sample_dates.values}")
    print(f"  Price index type: {type(prices.index[0])}")
    print(f"  Earnings date type: {type(sample_dates.iloc[0])}")
    print(f"  Price date range: {prices.index.min()} to {prices.index.max()}")

# Check 3: Timezone mismatch
sample_price_index = price_by_ticker[sample_tickers[0]].index
print(f"\nPrice index timezone: {sample_price_index.tz}")
print(f"Earnings date sample timezone: {df['earnings_date'].dt.tz}")

Transcript tickers:          2876
Price tickers available:     1274
Overlap (should match):      1274

Ticker: PLAB
  Earnings dates: ['2021-05-26T08:30:00.000000000' '2021-08-25T08:30:00.000000000'
 '2021-02-24T08:30:00.000000000']
  Price index type: <class 'pandas._libs.tslibs.timestamps.Timestamp'>
  Earnings date type: <class 'pandas._libs.tslibs.timestamps.Timestamp'>
  Price date range: 2017-01-03 00:00:00 to 2023-12-29 00:00:00

Ticker: JJSF
  Earnings dates: ['2022-11-15T10:00:00.000000000' '2021-04-27T10:00:00.000000000'
 '2021-07-27T10:00:00.000000000']
  Price index type: <class 'pandas._libs.tslibs.timestamps.Timestamp'>
  Earnings date type: <class 'pandas._libs.tslibs.timestamps.Timestamp'>
  Price date range: 2017-01-03 00:00:00 to 2023-12-29 00:00:00

Ticker: MSGE
  Earnings dates: ['2021-02-12T10:00:00.000000000' '2022-05-09T10:00:00.000000000'
 '2021-02-12T10:00:00.000000000']
  Price index type: <class 'pandas._libs.tslibs.timestamps.Timestamp'>
  Earnings date type

**Bug Fix — Earnings Date Time Component Mismatch:** During the initial run of the transcript-to-price join, only 224 out of 18,755 transcripts were successfully matched, with 18,531 rows skipped. Diagnostic investigation revealed that the earnings dates parsed from the Motley Fool pkl retain their original time components (e.g., `2021-05-26 08:30:00`, `2021-08-25 10:00:00`), since the raw `date` column stores full datetime strings including the call time in ET. The yfinance price index, however, stores dates as date-only timestamps normalized to midnight (e.g., `2021-05-26 00:00:00`). As a result, the lookup `if lookup_date in prices.index` always failed — Python cannot match `2021-05-26 08:30:00` against `2021-05-26 00:00:00` even though they represent the same calendar date. The fix is to apply `.dt.normalize()` to strip the time component from all earnings dates before the join, aligning them to midnight and enabling correct matching against the price index.

In [25]:
# ── Fix: normalize earnings_date to date-only (remove time component) ─────────
df['earnings_date'] = pd.to_datetime(df['earnings_date']).dt.normalize()

print("Sample earnings dates after normalization:")
print(df['earnings_date'].head(5))
print(f"\nSample price index:")
print(list(price_by_ticker[list(price_by_ticker.keys())[0]].index[:5]))

Sample earnings dates after normalization:
0   2020-08-27
1   2020-07-30
2   2019-10-23
3   2019-11-06
4   2019-08-07
Name: earnings_date, dtype: datetime64[ns]

Sample price index:
[Timestamp('2017-01-03 00:00:00'), Timestamp('2017-01-04 00:00:00'), Timestamp('2017-01-05 00:00:00'), Timestamp('2017-01-06 00:00:00'), Timestamp('2017-01-09 00:00:00')]


In [27]:
# ── Rebuild everything with normalized dates ──────────────────────────────────

# Step 1: Normalize both date columns
df['earnings_date'] = pd.to_datetime(df['earnings_date']).dt.normalize()
price_df['Date'] = pd.to_datetime(price_df['Date']).dt.normalize()

# Step 2: Verify normalization worked
print("Earnings date sample:", df['earnings_date'].head(3).tolist())
print("Price date sample:", price_df['Date'].head(3).tolist())

# Step 3: Rebuild price_by_ticker with normalized dates
price_by_ticker = {
    ticker: group.set_index('Date')['close']
    for ticker, group in price_df.groupby('ticker')
}

# Step 4: Verify a specific lookup works manually
test_ticker = 'PLAB'
test_date = pd.Timestamp('2021-05-26')
if test_ticker in price_by_ticker:
    prices = price_by_ticker[test_ticker]
    print(f"\nManual lookup test:")
    print(f"  Ticker: {test_ticker}")
    print(f"  Looking up: {test_date}")
    print(f"  Date in index: {test_date in prices.index}")
    print(f"  Nearby dates in index: {prices.index[prices.index >= test_date][:5].tolist()}")

Earnings date sample: [Timestamp('2020-08-27 00:00:00'), Timestamp('2020-07-30 00:00:00'), Timestamp('2019-10-23 00:00:00')]
Price date sample: [Timestamp('2017-01-03 00:00:00'), Timestamp('2017-01-04 00:00:00'), Timestamp('2017-01-05 00:00:00')]

Manual lookup test:
  Ticker: PLAB
  Looking up: 2021-05-26 00:00:00
  Date in index: True
  Nearby dates in index: [Timestamp('2021-05-26 00:00:00'), Timestamp('2021-05-27 00:00:00'), Timestamp('2021-05-28 00:00:00'), Timestamp('2021-06-01 00:00:00'), Timestamp('2021-06-02 00:00:00')]


In [28]:
# ── Rerun - Join Transcript to Price Data ────────────────────────────────────
results = []
skipped = 0

for idx, row in df.iterrows():
    ticker = row['ticker']
    earn_date = row['earnings_date']

    if ticker not in price_by_ticker:
        skipped += 1
        continue

    prices = price_by_ticker[ticker]

    try:
        # Get base price on or just after earnings date
        base_price = None
        for offset in range(6):
            lookup = earn_date + pd.Timedelta(days=offset)
            if lookup in prices.index:
                base_price = prices[lookup]
                break

        if base_price is None or pd.isna(base_price) or base_price == 0:
            skipped += 1
            continue

        price_5d  = get_nth_trading_day_price(prices, earn_date, 5)
        price_10d = get_nth_trading_day_price(prices, earn_date, 10)
        price_20d = get_nth_trading_day_price(prices, earn_date, 20)

        return_5d  = (price_5d  / base_price - 1) if not pd.isna(price_5d)  else np.nan
        return_10d = (price_10d / base_price - 1) if not pd.isna(price_10d) else np.nan
        return_20d = (price_20d / base_price - 1) if not pd.isna(price_20d) else np.nan

        results.append({
            'idx'       : idx,
            'base_price': base_price,
            'price_5d'  : price_5d,
            'price_10d' : price_10d,
            'price_20d' : price_20d,
            'return_5d' : return_5d,
            'return_10d': return_10d,
            'return_20d': return_20d,
            'label_5d'  : 1 if return_5d  > 0 else 0 if not pd.isna(return_5d)  else np.nan,
            'label_10d' : 1 if return_10d > 0 else 0 if not pd.isna(return_10d) else np.nan,
            'label_20d' : 1 if return_20d > 0 else 0 if not pd.isna(return_20d) else np.nan,
        })

    except Exception as e:
        skipped += 1
        continue

print(f"Successfully computed returns: {len(results)}")
print(f"Skipped (no price data):       {skipped}")

# ── Merge and save ────────────────────────────────────────────────────────────
results_df = pd.DataFrame(results).set_index('idx')
df = df.join(results_df, how='left', rsuffix='_new')

# Drop old return columns if they exist from previous run
for col in ['return_5d', 'return_10d', 'return_20d', 'label_5d', 'label_10d', 'label_20d']:
    if col + '_new' in df.columns:
        df[col] = df[col + '_new']
        df = df.drop(columns=[col + '_new'])

df_final = df.dropna(subset=['return_5d', 'return_10d', 'return_20d']).copy()

print(f"\nFinal usable tickers: {df_final['ticker'].nunique()}")
print(f"Final usable rows:    {len(df_final)}")

print(f"\nLabel distribution (5-day):")
print(df_final['label_5d'].value_counts())

# ── Save ──────────────────────────────────────────────────────────────────────
cols_to_save = [
    'ticker', 'earnings_date', 'q', 'earnings_date_is_approx',
    'transcript', 'transcript_clean', 'exec_text', 'analyst_text',
    'speaker_parse_success', 'return_5d', 'return_10d', 'return_20d',
    'label_5d', 'label_10d', 'label_20d'
]
existing_cols = [c for c in cols_to_save if c in df_final.columns]
df_final[existing_cols].to_csv('Data/cleaned_transcripts.csv', index=False)
print("\nSaved: Data/cleaned_transcripts.csv")

Successfully computed returns: 9599
Skipped (no price data):       9156

Final usable tickers: 1272
Final usable rows:    9599

Label distribution (5-day):
label_5d
1.0    5055
0.0    4544
Name: count, dtype: int64

Saved: Data/cleaned_transcripts.csv


**Re-fetching**

During the initial price data collection step, yfinance's rate limiter was triggered starting from batch 31 of 58, causing approximately 1,600 tickers to fail with a `YFRateLimitError` rather than a genuine "delisted" or "not found" error. These tickers were not missing from Yahoo Finance, they were simply rejected because too many requests were sent in too short a time window. As a result, the Join step could only match 9,599 of the 18,755 transcripts, leaving 9,156 rows without return labels despite their tickers potentially having valid price data. Re-fetching these tickers using smaller batch sizes (20 instead of 50) and longer pauses between requests (10 seconds instead of 0.5 seconds) allows yfinance to serve the data without triggering the rate limit. If successful, this could recover an additional 5,000–7,000 transcript rows, pushing the final training dataset from approximately 9,600 to potentially 14,000–16,000 rows, which is a 50–70% increase that meaningfully improves the generalizability of the ML models trained in later phase.

In [29]:
import yfinance as yf
import pandas as pd
import numpy as np
import time
import os

# ── Step 1: Identify tickers that were skipped in the join ───────────────────
# These are tickers in the transcript but NOT in price_by_ticker
# They were skipped due to rate limiting

tickers_in_transcripts = set(df['ticker'].dropna().unique())
tickers_with_prices    = set(price_by_ticker.keys())
tickers_to_refetch     = list(tickers_in_transcripts - tickers_with_prices)

print(f"Tickers in transcripts:    {len(tickers_in_transcripts)}")
print(f"Tickers with prices:       {len(tickers_with_prices)}")
print(f"Tickers to re-fetch:       {len(tickers_to_refetch)}")

# Save the list in case the re-fetch is interrupted
with open('Data/tickers_to_refetch.txt', 'w') as f:
    f.write('\n'.join(tickers_to_refetch))
print("Saved: Data/tickers_to_refetch.txt")

# ── Step 2: Re-fetch in small batches with longer pause ───────────────────────
BATCH_SIZE  = 20    # smaller than before to avoid rate limits
SLEEP_TIME  = 10    # seconds between batches

retry_prices  = []
still_failed  = []

print(f"\nRe-fetching {len(tickers_to_refetch)} tickers in batches of {BATCH_SIZE}...")

for i in range(0, len(tickers_to_refetch), BATCH_SIZE):
    batch = tickers_to_refetch[i:i + BATCH_SIZE]
    batch_str = ' '.join(batch)

    try:
        data = yf.download(
            batch_str,
            start='2017-01-01',
            end='2024-01-01',
            auto_adjust=True,
            progress=False
        )

        if data.empty:
            still_failed.extend(batch)
            print(f"  Batch {i//BATCH_SIZE + 1}: empty — skipping")
            time.sleep(SLEEP_TIME)
            continue

        # Extract Close prices
        if isinstance(data.columns, pd.MultiIndex):
            close_data = data['Close']
        else:
            close_data = data[['Close']]
            close_data.columns = [batch[0]]

        close_long = close_data.reset_index().melt(
            id_vars='Date',
            var_name='ticker',
            value_name='close'
        )
        close_long = close_long.dropna(subset=['close'])

        # Normalize dates immediately
        close_long['Date'] = pd.to_datetime(close_long['Date']).dt.normalize()

        retry_prices.append(close_long)
        print(f"  Batch {i//BATCH_SIZE + 1}/{(len(tickers_to_refetch)-1)//BATCH_SIZE + 1}: "
              f"{len(close_long)} rows, "
              f"{close_long['ticker'].nunique()} tickers")

    except Exception as e:
        still_failed.extend(batch)
        print(f"  Batch {i//BATCH_SIZE + 1}: FAILED — {str(e)[:60]}")

    time.sleep(SLEEP_TIME)

# ── Step 3: Combine new prices with existing price data ───────────────────────
print(f"\nRe-fetch complete.")
print(f"  Batches with data:  {len(retry_prices)}")
print(f"  Still failed:       {len(still_failed)} tickers")

if retry_prices:
    retry_df = pd.concat(retry_prices, ignore_index=True)
    retry_df['Date'] = pd.to_datetime(retry_df['Date']).dt.normalize()

    print(f"\nNew price rows fetched: {len(retry_df)}")
    print(f"New tickers fetched:    {retry_df['ticker'].nunique()}")

    # Combine with existing price_df
    price_df_updated = pd.concat([price_df, retry_df], ignore_index=True)
    price_df_updated = price_df_updated.drop_duplicates(subset=['Date', 'ticker'])
    price_df_updated = price_df_updated.sort_values(['ticker', 'Date']).reset_index(drop=True)

    print(f"\nUpdated price data:")
    print(f"  Total rows:    {len(price_df_updated)}")
    print(f"  Total tickers: {price_df_updated['ticker'].nunique()}")

    # Save updated price data
    price_df_updated.to_csv('Data/stock_prices_updated.csv', index=False)
    print("\nSaved: Data/stock_prices_updated.csv")

    # ── Step 4: Rebuild price_by_ticker with new data ─────────────────────────
    price_df = price_df_updated.copy()
    price_by_ticker = {
        ticker: group.set_index('Date')['close']
        for ticker, group in price_df.groupby('ticker')
    }
    print(f"Rebuilt price_by_ticker with {len(price_by_ticker)} tickers")

else:
    print("\nNo new prices fetched — price_by_ticker unchanged")

# ── Step 5: Save still-failed tickers for reference ──────────────────────────
if still_failed:
    with open('Data/tickers_still_failed.txt', 'w') as f:
        f.write('\n'.join(still_failed))
    print(f"\nSaved {len(still_failed)} still-failed tickers: Data/tickers_still_failed.txt")

Tickers in transcripts:    2876
Tickers with prices:       1274
Tickers to re-fetch:       1602
Saved: Data/tickers_to_refetch.txt

Re-fetching 1602 tickers in batches of 20...


$PHX: possibly delisted; no timezone found
$ATGE: possibly delisted; no timezone found
$RVNC: possibly delisted; no timezone found
$IVC: possibly delisted; no timezone found
$AXU: possibly delisted; no timezone found
$LHDX: possibly delisted; no timezone found
$VAPO: possibly delisted; no timezone found
$DMS: possibly delisted; no timezone found
$PRMW: possibly delisted; no timezone found
$STER: possibly delisted; no timezone found
$BCEI: possibly delisted; no timezone found
$RAD: possibly delisted; no timezone found

13 Failed downloads:
['PHX', 'ATGE', 'RVNC', 'IVC', 'AXU', 'LHDX', 'VAPO', 'DMS', 'PRMW', 'STER', 'BCEI', 'RAD']: possibly delisted; no timezone found
['ECHO']: YFRateLimitError('Too Many Requests. Rate limited. Try after a while.')


  Batch 1/81: 12320 rows, 7 tickers


$SHSP: possibly delisted; no timezone found
$JAMF: possibly delisted; no timezone found
$OMI: possibly delisted; no timezone found
$DISC.A: possibly delisted; no timezone found
$IRBT: possibly delisted; no timezone found
$RTLR: possibly delisted; no timezone found
$HRC: possibly delisted; no timezone found
$EVOP: possibly delisted; no timezone found

8 Failed downloads:
['SHSP', 'JAMF', 'OMI', 'DISC.A', 'IRBT', 'RTLR', 'HRC', 'EVOP']: possibly delisted; no timezone found


  Batch 2/81: 20842 rows, 12 tickers


$STNG): possibly delisted; no timezone found
$PGTI: possibly delisted; no timezone found
$FCAU: possibly delisted; no timezone found
$SLCA: possibly delisted; no timezone found
$SIR): possibly delisted; no timezone found
$EDR: possibly delisted; no timezone found

6 Failed downloads:
['STNG)', 'PGTI', 'FCAU', 'SLCA', 'SIR)', 'EDR']: possibly delisted; no timezone found


  Batch 3/81: 23211 rows, 14 tickers


$SYNH: possibly delisted; no timezone found
$SWAV: possibly delisted; no timezone found
$SCU: possibly delisted; no timezone found
$SQ: possibly delisted; no timezone found
$QRTEA: possibly delisted; no timezone found

5 Failed downloads:
['SYNH', 'SWAV', 'SCU', 'SQ', 'QRTEA']: possibly delisted; no timezone found


  Batch 4/81: 24287 rows, 15 tickers


$DCFC: possibly delisted; no timezone found
$EAR: possibly delisted; no timezone found
$SOVO: possibly delisted; no timezone found
$DADA: possibly delisted; no timezone found
$NTCO: possibly delisted; no timezone found
$IDEX: possibly delisted; no timezone found
$PSXP: possibly delisted; no timezone found
$ENV: possibly delisted; no timezone found
$DOOO: possibly delisted; no timezone found

9 Failed downloads:
['DCFC', 'EAR', 'SOVO', 'DADA', 'NTCO', 'IDEX', 'PSXP', 'ENV', 'DOOO']: possibly delisted; no timezone found


  Batch 5/81: 15953 rows, 11 tickers


$NYCB: possibly delisted; no timezone found
$WBT: possibly delisted; no timezone found
$WLL: possibly delisted; no timezone found
$UNVR: possibly delisted; no timezone found
$MXIM: possibly delisted; no timezone found
$BF.B: possibly delisted; no price data found  (1d 2017-01-01 -> 2024-01-01)
$ITI: possibly delisted; no timezone found
$GBT: possibly delisted; no timezone found

8 Failed downloads:
['NYCB', 'WBT', 'WLL', 'UNVR', 'MXIM', 'ITI', 'GBT']: possibly delisted; no timezone found
['BF.B']: possibly delisted; no price data found  (1d 2017-01-01 -> 2024-01-01)


  Batch 6/81: 17917 rows, 12 tickers


$HMST: possibly delisted; no timezone found
$SWN: possibly delisted; no timezone found
$MRO: possibly delisted; no timezone found
$DRQ: possibly delisted; no timezone found
$ALTR: possibly delisted; no timezone found
$SFT: possibly delisted; no timezone found

6 Failed downloads:
['HMST', 'SWN', 'MRO', 'DRQ', 'ALTR', 'SFT']: possibly delisted; no timezone found


  Batch 7/81: 21929 rows, 14 tickers


$NEWR: possibly delisted; no timezone found
$HEAR: possibly delisted; no timezone found
$WRK: possibly delisted; no timezone found
$FOCS: possibly delisted; no timezone found
$SDC: possibly delisted; no timezone found
$INT: possibly delisted; no timezone found

6 Failed downloads:
['NEWR', 'HEAR', 'WRK', 'FOCS', 'SDC', 'INT']: possibly delisted; no timezone found


  Batch 8/81: 21169 rows, 14 tickers


$VMW: possibly delisted; no timezone found
$TSU: possibly delisted; no timezone found
$DCPH: possibly delisted; no timezone found
$PEIX): possibly delisted; no timezone found
$EGLE: possibly delisted; no price data found  (1d 2017-01-01 -> 2024-01-01) (Yahoo error = "Data doesn't exist for startDate = 1483246800, endDate = 1704085200")
$DCT: possibly delisted; no timezone found
$VRAY: possibly delisted; no timezone found
$SIEN: possibly delisted; no timezone found
$CCMP: possibly delisted; no timezone found
$AIRC: possibly delisted; no timezone found
$EVRI: possibly delisted; no timezone found
$GLOP: possibly delisted; no timezone found

12 Failed downloads:
['VMW', 'TSU', 'DCPH', 'PEIX)', 'DCT', 'VRAY', 'SIEN', 'CCMP', 'AIRC', 'EVRI', 'GLOP']: possibly delisted; no timezone found
['EGLE']: possibly delisted; no price data found  (1d 2017-01-01 -> 2024-01-01) (Yahoo error = "Data doesn't exist for startDate = 1483246800, endDate = 1704085200")


  Batch 9/81: 12348 rows, 8 tickers


$THRN: possibly delisted; no timezone found
$TGNA: possibly delisted; no timezone found
$NVRO: possibly delisted; no timezone found
$OFC: possibly delisted; no timezone found
$IAS: possibly delisted; no price data found  (1d 2017-01-01 -> 2024-01-01)
$BKCC: possibly delisted; no timezone found

6 Failed downloads:
['THRN', 'TGNA', 'NVRO', 'OFC', 'BKCC']: possibly delisted; no timezone found
['IAS']: possibly delisted; no price data found  (1d 2017-01-01 -> 2024-01-01)


  Batch 10/81: 23440 rows, 14 tickers


$CMRX: possibly delisted; no timezone found
$CVET: possibly delisted; no timezone found
$JOAN: possibly delisted; no timezone found
$RDFN: possibly delisted; no timezone found
$PRTY: possibly delisted; no timezone found
$TIG: possibly delisted; no timezone found
$SNV: possibly delisted; no timezone found
$PYCR: possibly delisted; no timezone found
$JT: possibly delisted; no timezone found
$AGRX: possibly delisted; no timezone found
$OMIC: possibly delisted; no timezone found
$VTOL): possibly delisted; no timezone found
$ZNGA: possibly delisted; no timezone found

13 Failed downloads:
['CMRX', 'CVET', 'JOAN', 'RDFN', 'PRTY', 'TIG', 'SNV', 'PYCR', 'JT', 'AGRX', 'OMIC', 'VTOL)', 'ZNGA']: possibly delisted; no timezone found


  Batch 11/81: 11643 rows, 7 tickers


$SJW: possibly delisted; no timezone found
$HTLF: possibly delisted; no timezone found
$ARNC: possibly delisted; no timezone found
$PKI: possibly delisted; no timezone found
$TERP: possibly delisted; no timezone found
$TSE: possibly delisted; no timezone found
$EQC: possibly delisted; no timezone found

7 Failed downloads:
['SJW', 'HTLF', 'ARNC', 'PKI', 'TERP', 'TSE', 'EQC']: possibly delisted; no timezone found


  Batch 12/81: 18742 rows, 13 tickers


$WIRE: possibly delisted; no timezone found
$WKME): possibly delisted; no timezone found
$ERJ: possibly delisted; no timezone found
$MGIC: possibly delisted; no timezone found
$CBAY: possibly delisted; no timezone found
$AX.DL: possibly delisted; no timezone found
$ATTO: possibly delisted; no timezone found
$CO: possibly delisted; no timezone found
$VLDR: possibly delisted; no timezone found
$BRG: possibly delisted; no timezone found

10 Failed downloads:
['WIRE', 'WKME)', 'ERJ', 'MGIC', 'CBAY', 'AX.DL', 'ATTO', 'CO', 'VLDR', 'BRG']: possibly delisted; no timezone found


  Batch 13/81: 17600 rows, 10 tickers


$CFLT: possibly delisted; no timezone found
$ICAD: possibly delisted; no timezone found
$BEST: possibly delisted; no timezone found
$CPLG: possibly delisted; no timezone found
$UFS: possibly delisted; no timezone found
$CPE: possibly delisted; no timezone found
$FLY: possibly delisted; no price data found  (1d 2017-01-01 -> 2024-01-01) (Yahoo error = "Data doesn't exist for startDate = 1483246800, endDate = 1704085200")

7 Failed downloads:
['CFLT', 'ICAD', 'BEST', 'CPLG', 'UFS', 'CPE']: possibly delisted; no timezone found
['FLY']: possibly delisted; no price data found  (1d 2017-01-01 -> 2024-01-01) (Yahoo error = "Data doesn't exist for startDate = 1483246800, endDate = 1704085200")


  Batch 14/81: 19797 rows, 13 tickers


$MYOV: possibly delisted; no timezone found
$CSII: possibly delisted; no timezone found
$REPH: possibly delisted; no timezone found
$BLFY: possibly delisted; no timezone found
$GAN: possibly delisted; no timezone found
$NUVA: possibly delisted; no timezone found
$NTUS: possibly delisted; no timezone found
$CMRE): possibly delisted; no timezone found
$CXP: possibly delisted; no timezone found
$VGR: possibly delisted; no timezone found
$ENLC: possibly delisted; no timezone found
$SHYF: possibly delisted; no timezone found
$CTK: possibly delisted; no timezone found

13 Failed downloads:
['MYOV', 'CSII', 'REPH', 'BLFY', 'GAN', 'NUVA', 'NTUS', 'CMRE)', 'CXP', 'VGR', 'ENLC', 'SHYF', 'CTK']: possibly delisted; no timezone found


  Batch 15/81: 11176 rows, 7 tickers


$HHC: possibly delisted; no timezone found
$ONDK: possibly delisted; no timezone found
$VRM: possibly delisted; no price data found  (1d 2017-01-01 -> 2024-01-01) (Yahoo error = "Data doesn't exist for startDate = 1483246800, endDate = 1704085200")
$INFN: possibly delisted; no timezone found
$SRCL: possibly delisted; no timezone found
$REDU: possibly delisted; no timezone found
$CONN: possibly delisted; no timezone found
$MIME: possibly delisted; no timezone found
$IEA: possibly delisted; no timezone found

9 Failed downloads:
['HHC', 'ONDK', 'INFN', 'SRCL', 'REDU', 'CONN', 'MIME', 'IEA']: possibly delisted; no timezone found
['VRM']: possibly delisted; no price data found  (1d 2017-01-01 -> 2024-01-01) (Yahoo error = "Data doesn't exist for startDate = 1483246800, endDate = 1704085200")


  Batch 16/81: 17091 rows, 11 tickers


$COUP: possibly delisted; no timezone found
$NCR: possibly delisted; no timezone found
$EXPR: possibly delisted; no timezone found
$OCSI: possibly delisted; no timezone found
$EWCZ: possibly delisted; no price data found  (1d 2017-01-01 -> 2024-01-01)
$TEF: possibly delisted; no timezone found
$TGH: possibly delisted; no timezone found
$LHCG: possibly delisted; no timezone found
$ACCD: possibly delisted; no timezone found
$CDK: possibly delisted; no timezone found
$AMBC: possibly delisted; no timezone found

11 Failed downloads:
['COUP', 'NCR', 'EXPR', 'OCSI', 'TEF', 'TGH', 'LHCG', 'ACCD', 'CDK', 'AMBC']: possibly delisted; no timezone found
['EWCZ']: possibly delisted; no price data found  (1d 2017-01-01 -> 2024-01-01)


  Batch 17/81: 13082 rows, 9 tickers


$DSSI: possibly delisted; no timezone found
$OTIC: possibly delisted; no timezone found
$ABTX: possibly delisted; no timezone found
$PCH: possibly delisted; no timezone found
$SRDX: possibly delisted; no timezone found
$CTIC: possibly delisted; no timezone found
$WEBR: possibly delisted; no timezone found
$CERN: possibly delisted; no timezone found
$DYNC): possibly delisted; no timezone found

9 Failed downloads:
['DSSI', 'OTIC', 'ABTX', 'PCH', 'SRDX', 'CTIC', 'WEBR', 'CERN', 'DYNC)']: possibly delisted; no timezone found


  Batch 18/81: 18006 rows, 11 tickers


$EURN: possibly delisted; no timezone found
$GWB: possibly delisted; no timezone found
$HT: possibly delisted; no timezone found
$GLT: possibly delisted; no timezone found
$RAAS: possibly delisted; no timezone found

5 Failed downloads:
['EURN', 'GWB', 'HT', 'GLT', 'RAAS']: possibly delisted; no timezone found


  Batch 19/81: 24289 rows, 15 tickers


$WPX: possibly delisted; no timezone found
$AGL): possibly delisted; no timezone found
$LBRD.A: possibly delisted; no timezone found
$FSR: possibly delisted; no timezone found
$ALBO: possibly delisted; no timezone found
$HSII: possibly delisted; no timezone found
$AVDL: possibly delisted; no timezone found
$BIG: possibly delisted; no timezone found
$BGCP: possibly delisted; no timezone found
$FTCH: possibly delisted; no timezone found

10 Failed downloads:
['WPX', 'AGL)', 'LBRD.A', 'FSR', 'ALBO', 'HSII', 'AVDL', 'BIG', 'BGCP', 'FTCH']: possibly delisted; no timezone found


  Batch 20/81: 14348 rows, 10 tickers


$CFX: possibly delisted; no timezone found
$K: possibly delisted; no timezone found
$MR: possibly delisted; no timezone found
$PTR: possibly delisted; no timezone found
$EBIX: possibly delisted; no timezone found
$TPX: possibly delisted; no timezone found
$FLT: possibly delisted; no timezone found
$FUV: possibly delisted; no timezone found
$ROLL: possibly delisted; no timezone found
$WKME: possibly delisted; no timezone found
$OPI: possibly delisted; no timezone found
$SAIL: possibly delisted; no price data found  (1d 2017-01-01 -> 2024-01-01) (Yahoo error = "Data doesn't exist for startDate = 1483246800, endDate = 1704085200")

12 Failed downloads:
['CFX', 'K', 'MR', 'PTR', 'EBIX', 'TPX', 'FLT', 'FUV', 'ROLL', 'WKME', 'OPI']: possibly delisted; no timezone found
['SAIL']: possibly delisted; no price data found  (1d 2017-01-01 -> 2024-01-01) (Yahoo error = "Data doesn't exist for startDate = 1483246800, endDate = 1704085200")


  Batch 21/81: 13817 rows, 8 tickers


$AGS: possibly delisted; no timezone found
$ADN: possibly delisted; no timezone found
$APTO: possibly delisted; no timezone found
$IGIC): possibly delisted; no timezone found
$GPP: possibly delisted; no timezone found
$PRVB: possibly delisted; no timezone found
$BKI: possibly delisted; no timezone found
$DNB: possibly delisted; no timezone found
$KNBE: possibly delisted; no timezone found

9 Failed downloads:
['AGS', 'ADN', 'APTO', 'IGIC)', 'GPP', 'PRVB', 'BKI', 'DNB', 'KNBE']: possibly delisted; no timezone found


  Batch 22/81: 15021 rows, 11 tickers


$PLYM: possibly delisted; no timezone found
$TLIS): possibly delisted; no timezone found
$ZYXI: possibly delisted; no timezone found
$OTRK: possibly delisted; no price data found  (1d 2017-01-01 -> 2024-01-01) (Yahoo error = "Data doesn't exist for startDate = 1483246800, endDate = 1704085200")
$CNTG: possibly delisted; no timezone found
$GATO: possibly delisted; no timezone found
$TRHC: possibly delisted; no timezone found
$ZEUS: possibly delisted; no timezone found
$DESP: possibly delisted; no timezone found
$HOLX: possibly delisted; no timezone found

10 Failed downloads:
['PLYM', 'TLIS)', 'ZYXI', 'CNTG', 'GATO', 'TRHC', 'ZEUS', 'DESP', 'HOLX']: possibly delisted; no timezone found
['OTRK']: possibly delisted; no price data found  (1d 2017-01-01 -> 2024-01-01) (Yahoo error = "Data doesn't exist for startDate = 1483246800, endDate = 1704085200")


  Batch 23/81: 14507 rows, 10 tickers


$CPLP: possibly delisted; no timezone found
$LIVX: possibly delisted; no timezone found
$MYOK: possibly delisted; no timezone found
$VRS: possibly delisted; no timezone found
$QTNT: possibly delisted; no timezone found
$BPMC: possibly delisted; no timezone found
$PROG: possibly delisted; no timezone found
$SI: possibly delisted; no price data found  (1d 2017-01-01 -> 2024-01-01) (Yahoo error = "Data doesn't exist for startDate = 1483246800, endDate = 1704085200")
$JNPR: possibly delisted; no timezone found
$ATUS: possibly delisted; no timezone found

10 Failed downloads:
['CPLP', 'LIVX', 'MYOK', 'VRS', 'QTNT', 'BPMC', 'PROG', 'JNPR', 'ATUS']: possibly delisted; no timezone found
['SI']: possibly delisted; no price data found  (1d 2017-01-01 -> 2024-01-01) (Yahoo error = "Data doesn't exist for startDate = 1483246800, endDate = 1704085200")


  Batch 24/81: 15062 rows, 10 tickers


$VALN): possibly delisted; no timezone found
$VIAO: possibly delisted; no timezone found
$EPZM: possibly delisted; no timezone found
$NLTX: possibly delisted; no timezone found
$WUBA: possibly delisted; no timezone found
$AZPN: possibly delisted; no timezone found

6 Failed downloads:
['VALN)', 'VIAO', 'EPZM', 'NLTX', 'WUBA', 'AZPN']: possibly delisted; no timezone found


  Batch 25/81: 18554 rows, 14 tickers


$WETF: possibly delisted; no timezone found
$HOUS: possibly delisted; no timezone found
$TTPH: possibly delisted; no timezone found
$FOE: possibly delisted; no timezone found
$MRLN: possibly delisted; no price data found  (1d 2017-01-01 -> 2024-01-01) (Yahoo error = "Data doesn't exist for startDate = 1483246800, endDate = 1704085200")
$SWIR: possibly delisted; no timezone found
$DEN: possibly delisted; no timezone found

7 Failed downloads:
['WETF', 'HOUS', 'TTPH', 'FOE', 'SWIR', 'DEN']: possibly delisted; no timezone found
['MRLN']: possibly delisted; no price data found  (1d 2017-01-01 -> 2024-01-01) (Yahoo error = "Data doesn't exist for startDate = 1483246800, endDate = 1704085200")


  Batch 26/81: 21014 rows, 13 tickers


$EB: possibly delisted; no timezone found
$ADMS: possibly delisted; no timezone found
$BGFV: possibly delisted; no timezone found
$NEPT: possibly delisted; no timezone found
$PWFL: possibly delisted; no timezone found
$CARA: possibly delisted; no timezone found

6 Failed downloads:
['EB', 'ADMS', 'BGFV', 'NEPT', 'PWFL', 'CARA']: possibly delisted; no timezone found


  Batch 27/81: 18425 rows, 14 tickers


$BHG: possibly delisted; no timezone found
$COWN: possibly delisted; no timezone found
$FORG: possibly delisted; no timezone found
$SRT: possibly delisted; no timezone found
$APTX: possibly delisted; no timezone found
$SIVB: possibly delisted; no timezone found
$MESA: possibly delisted; no timezone found
$UMPQ: possibly delisted; no timezone found
$ITCI: possibly delisted; no timezone found
$NVTA: possibly delisted; no timezone found
$OB: possibly delisted; no timezone found
$YY: possibly delisted; no timezone found
$TDCX: possibly delisted; no timezone found

13 Failed downloads:
['COWN', 'BHG', 'FORG', 'SRT', 'APTX', 'SIVB', 'MESA', 'UMPQ', 'ITCI', 'NVTA', 'OB', 'YY', 'TDCX']: possibly delisted; no timezone found


  Batch 28/81: 11854 rows, 7 tickers


$AXL: possibly delisted; no timezone found
$NKLA: possibly delisted; no timezone found
$AZEK: possibly delisted; no timezone found
$BDSI: possibly delisted; no timezone found
$RDUS: possibly delisted; no timezone found
$COMM: possibly delisted; no timezone found
$CHS: possibly delisted; no timezone found
$SWIM): possibly delisted; no timezone found

8 Failed downloads:
['AXL', 'NKLA', 'AZEK', 'BDSI', 'RDUS', 'COMM', 'CHS', 'SWIM)']: possibly delisted; no timezone found


  Batch 29/81: 17918 rows, 12 tickers


$ATAX: possibly delisted; no timezone found
$FL: possibly delisted; no timezone found
$REVG: possibly delisted; no timezone found
$STOR: possibly delisted; no timezone found
$AZRE: possibly delisted; no timezone found
$VNE: possibly delisted; no timezone found
$FARO: possibly delisted; no timezone found
$RAIN): possibly delisted; no timezone found
$ZY: possibly delisted; no timezone found
$WDR: possibly delisted; no timezone found

10 Failed downloads:
['ATAX', 'FL', 'REVG', 'STOR', 'AZRE', 'VNE', 'FARO', 'RAIN)', 'ZY', 'WDR']: possibly delisted; no timezone found


  Batch 30/81: 16547 rows, 10 tickers


$KRA: possibly delisted; no timezone found
$HES: possibly delisted; no timezone found
$FRG: possibly delisted; no timezone found
$TSP: possibly delisted; no timezone found
$FRGI: possibly delisted; no timezone found
$ATC): possibly delisted; no timezone found

6 Failed downloads:
['KRA', 'HES', 'FRG', 'TSP', 'FRGI', 'ATC)']: possibly delisted; no timezone found


  Batch 31/81: 23327 rows, 14 tickers


$PEAK: possibly delisted; no timezone found
$MTOR: possibly delisted; no timezone found
$CMD: possibly delisted; no timezone found
$RESN: possibly delisted; no timezone found
$BPMP: possibly delisted; no timezone found
$PDCO: possibly delisted; no timezone found
$VRTV: possibly delisted; no timezone found
$IMV: possibly delisted; no timezone found
$OYST: possibly delisted; no timezone found
$MPLN: possibly delisted; no timezone found
$PLTK): possibly delisted; no timezone found

11 Failed downloads:
['PEAK', 'MTOR', 'CMD', 'RESN', 'BPMP', 'PDCO', 'VRTV', 'IMV', 'OYST', 'MPLN', 'PLTK)']: possibly delisted; no timezone found


  Batch 32/81: 15393 rows, 9 tickers


$JWN: possibly delisted; no timezone found
$SUM: possibly delisted; no timezone found
$BHLB: possibly delisted; no timezone found
$ZLND.Y: possibly delisted; no timezone found
$IPG: possibly delisted; no timezone found
$LNDC: possibly delisted; no timezone found
$AIMC: possibly delisted; no timezone found
$PFHC: possibly delisted; no timezone found

8 Failed downloads:
['JWN', 'SUM', 'BHLB', 'ZLND.Y', 'IPG', 'LNDC', 'AIMC', 'PFHC']: possibly delisted; no timezone found


  Batch 33/81: 19200 rows, 12 tickers


$ADV): possibly delisted; no timezone found
$PLYA: possibly delisted; no timezone found
$TWTR: possibly delisted; no timezone found
$VIE: possibly delisted; no timezone found
$CHX: possibly delisted; no timezone found
$ETM: possibly delisted; no timezone found
$HSC: possibly delisted; no timezone found

7 Failed downloads:
['ADV)', 'PLYA', 'TWTR', 'VIE', 'CHX', 'ETM', 'HSC']: possibly delisted; no timezone found


  Batch 34/81: 20069 rows, 13 tickers


$ABC: possibly delisted; no timezone found
$TGI: possibly delisted; no timezone found
$CTXS: possibly delisted; no timezone found
$DVAX: possibly delisted; no timezone found
$AINV: possibly delisted; no timezone found
$PRTK: possibly delisted; no timezone found
$AFMD: possibly delisted; no price data found  (1d 2017-01-01 -> 2024-01-01)
$ZI: possibly delisted; no timezone found
$VVI: possibly delisted; no timezone found
$CHUY: possibly delisted; no timezone found
$PING: possibly delisted; no timezone found
$SPLK: possibly delisted; no timezone found
$SJI: possibly delisted; no timezone found
$MLNK: possibly delisted; no timezone found

14 Failed downloads:
['ABC', 'TGI', 'CTXS', 'DVAX', 'AINV', 'PRTK', 'ZI', 'VVI', 'CHUY', 'PING', 'SPLK', 'SJI', 'MLNK']: possibly delisted; no timezone found
['AFMD']: possibly delisted; no price data found  (1d 2017-01-01 -> 2024-01-01)


  Batch 35/81: 9540 rows, 6 tickers


$POSH: possibly delisted; no timezone found
$ATHX: possibly delisted; no timezone found
$ATSG: possibly delisted; no timezone found
$ARNA: possibly delisted; no timezone found
$ETRN: possibly delisted; no timezone found
$BCOV: possibly delisted; no timezone found
$NGMS: possibly delisted; no timezone found
$ANH: possibly delisted; no timezone found
$AGTI: possibly delisted; no timezone found

9 Failed downloads:
['POSH', 'ATHX', 'ATSG', 'ARNA', 'ETRN', 'BCOV', 'NGMS', 'ANH', 'AGTI']: possibly delisted; no timezone found


  Batch 36/81: 17428 rows, 11 tickers


$BIO.B: possibly delisted; no price data found  (1d 2017-01-01 -> 2024-01-01)
$RADA: possibly delisted; no timezone found
$GHL: possibly delisted; no timezone found
$MCW: possibly delisted; no price data found  (1d 2017-01-01 -> 2024-01-01)
$GMDA: possibly delisted; no timezone found
$AEGN: possibly delisted; no timezone found
$RAIN: possibly delisted; no price data found  (1d 2017-01-01 -> 2024-01-01) (Yahoo error = "Data doesn't exist for startDate = 1483246800, endDate = 1704085200")

7 Failed downloads:
['BIO.B', 'MCW']: possibly delisted; no price data found  (1d 2017-01-01 -> 2024-01-01)
['RADA', 'GHL', 'GMDA', 'AEGN']: possibly delisted; no timezone found
['RAIN']: possibly delisted; no price data found  (1d 2017-01-01 -> 2024-01-01) (Yahoo error = "Data doesn't exist for startDate = 1483246800, endDate = 1704085200")


  Batch 37/81: 19525 rows, 13 tickers


$EXTN: possibly delisted; no timezone found
$EBR: possibly delisted; no timezone found
$DRE: possibly delisted; no timezone found
$MODG: possibly delisted; no timezone found
$CDEV: possibly delisted; no timezone found

5 Failed downloads:
['EXTN', 'EBR', 'DRE', 'MODG', 'CDEV']: possibly delisted; no timezone found


  Batch 38/81: 24386 rows, 15 tickers


$NR: possibly delisted; no timezone found
$SUMO: possibly delisted; no timezone found
$XM: possibly delisted; no timezone found
$CSPR: possibly delisted; no timezone found
$GMS: possibly delisted; no timezone found
$LCI: possibly delisted; no timezone found
$PTVE: possibly delisted; no timezone found
$RRD: possibly delisted; no timezone found
$HMLP: possibly delisted; no timezone found
$BRKL: possibly delisted; no timezone found

10 Failed downloads:
['NR', 'SUMO', 'XM', 'CSPR', 'GMS', 'LCI', 'PTVE', 'RRD', 'HMLP', 'BRKL']: possibly delisted; no timezone found


  Batch 39/81: 15231 rows, 10 tickers


$TPRE: possibly delisted; no timezone found
$REGI: possibly delisted; no timezone found
$SCHN: possibly delisted; no timezone found
$ARGO: possibly delisted; no timezone found
$HAYN: possibly delisted; no timezone found

5 Failed downloads:
['TPRE', 'REGI', 'SCHN', 'ARGO', 'HAYN']: possibly delisted; no timezone found


  Batch 40/81: 24213 rows, 15 tickers


$JE: possibly delisted; no timezone found
$GOL: possibly delisted; no timezone found
$STXB: possibly delisted; no timezone found
$ONTF: possibly delisted; no timezone found
$AUY: possibly delisted; no timezone found
$ALE: possibly delisted; no timezone found
$GLIBA: possibly delisted; no price data found  (1d 2017-01-01 -> 2024-01-01) (Yahoo error = "Data doesn't exist for startDate = 1483246800, endDate = 1704085200")
$CBD: possibly delisted; no timezone found
$CEQP: possibly delisted; no timezone found
$AWH: possibly delisted; no timezone found
$CPG: possibly delisted; no timezone found
$LPI: possibly delisted; no timezone found

12 Failed downloads:
['JE', 'GOL', 'STXB', 'ONTF', 'AUY', 'ALE', 'CBD', 'CEQP', 'AWH', 'CPG', 'LPI']: possibly delisted; no timezone found
['GLIBA']: possibly delisted; no price data found  (1d 2017-01-01 -> 2024-01-01) (Yahoo error = "Data doesn't exist for startDate = 1483246800, endDate = 1704085200")


  Batch 41/81: 9062 rows, 8 tickers


$CVIA: possibly delisted; no timezone found
$COOP: possibly delisted; no timezone found
$ACRX: possibly delisted; no timezone found
$BSIG: possibly delisted; no timezone found
$AMED: possibly delisted; no timezone found
$AGFY: possibly delisted; no timezone found
$SMLP: possibly delisted; no timezone found

7 Failed downloads:
['CVIA', 'COOP', 'ACRX', 'BSIG', 'AMED', 'AGFY', 'SMLP']: possibly delisted; no timezone found


  Batch 42/81: 17273 rows, 13 tickers


$CDXC: possibly delisted; no timezone found
$HI: possibly delisted; no timezone found
$CS: possibly delisted; no timezone found
$WRE: possibly delisted; no timezone found
$AY: possibly delisted; no timezone found
$ORCC: possibly delisted; no timezone found
$BASE: possibly delisted; no timezone found
$SBNY: possibly delisted; no price data found  (1d 2017-01-01 -> 2024-01-01) (Yahoo error = "Data doesn't exist for startDate = 1483246800, endDate = 1704085200")
$SNCR: possibly delisted; no timezone found
$AXE: possibly delisted; no timezone found

10 Failed downloads:
['CDXC', 'HI', 'CS', 'WRE', 'AY', 'ORCC', 'BASE', 'SNCR', 'AXE']: possibly delisted; no timezone found
['SBNY']: possibly delisted; no price data found  (1d 2017-01-01 -> 2024-01-01) (Yahoo error = "Data doesn't exist for startDate = 1483246800, endDate = 1704085200")


  Batch 43/81: 16536 rows, 10 tickers


$TRMR: possibly delisted; no timezone found
$SMAR: possibly delisted; no timezone found
$HEP: possibly delisted; no timezone found
$AAIC: possibly delisted; no timezone found
$CMLS: possibly delisted; no timezone found
$LL: possibly delisted; no timezone found

6 Failed downloads:
['TRMR', 'SMAR', 'HEP', 'AAIC', 'CMLS', 'LL']: possibly delisted; no timezone found


  Batch 44/81: 21917 rows, 14 tickers


$GLYC: possibly delisted; no timezone found
$AHH: possibly delisted; no timezone found
$DENN: possibly delisted; no timezone found
$BALY: possibly delisted; no price data found  (1d 2017-01-01 -> 2024-01-01) (Yahoo error = "Data doesn't exist for startDate = 1483246800, endDate = 1704085200")
$IDSY: possibly delisted; no timezone found
$ZEAL: possibly delisted; no timezone found
$VIAB: possibly delisted; no timezone found
$ACC: possibly delisted; no timezone found
$LNW: possibly delisted; no price data found  (1d 2017-01-01 -> 2024-01-01) (Yahoo error = "Data doesn't exist for startDate = 1483246800, endDate = 1704085200")
$JW.A: possibly delisted; no timezone found

10 Failed downloads:
['GLYC', 'AHH', 'DENN', 'IDSY', 'ZEAL', 'VIAB', 'ACC', 'JW.A']: possibly delisted; no timezone found
['BALY', 'LNW']: possibly delisted; no price data found  (1d 2017-01-01 -> 2024-01-01) (Yahoo error = "Data doesn't exist for startDate = 1483246800, endDate = 1704085200")


  Batch 45/81: 16484 rows, 10 tickers


$RTL: possibly delisted; no timezone found
$SHLX: possibly delisted; no timezone found
$GTHX: possibly delisted; no timezone found
$EGIO: possibly delisted; no timezone found
$VCRA: possibly delisted; no timezone found
$TIXT: possibly delisted; no timezone found
$LSI: possibly delisted; no timezone found

7 Failed downloads:
['RTL', 'SHLX', 'GTHX', 'EGIO', 'VCRA', 'TIXT', 'LSI']: possibly delisted; no timezone found


  Batch 46/81: 16801 rows, 13 tickers


$AYX: possibly delisted; no timezone found
$CSSE: possibly delisted; no timezone found
$PSB: possibly delisted; no timezone found
$ITCB: possibly delisted; no timezone found
$GWGH): possibly delisted; no timezone found
$BERY: possibly delisted; no timezone found
$XEC: possibly delisted; no timezone found

7 Failed downloads:
['AYX', 'CSSE', 'PSB', 'ITCB', 'GWGH)', 'BERY', 'XEC']: possibly delisted; no timezone found


  Batch 47/81: 20940 rows, 13 tickers


$MCG: possibly delisted; no timezone found
$CUTR: possibly delisted; no timezone found
$ECOL: possibly delisted; no timezone found
$HBI: possibly delisted; no timezone found
$CEIX: possibly delisted; no timezone found
$ARD: possibly delisted; no timezone found
$ABB: possibly delisted; no timezone found
$AMSWA: possibly delisted; no timezone found
$CNCE: possibly delisted; no timezone found

9 Failed downloads:
['MCG', 'CUTR', 'ECOL', 'HBI', 'CEIX', 'ARD', 'ABB', 'AMSWA', 'CNCE']: possibly delisted; no timezone found


  Batch 48/81: 19360 rows, 11 tickers


$VSTO: possibly delisted; no timezone found
$TRUE: possibly delisted; no timezone found
$CNHI: possibly delisted; no timezone found

3 Failed downloads:
['VSTO', 'TRUE', 'CNHI']: possibly delisted; no timezone found


  Batch 49/81: 26187 rows, 17 tickers


$FRC: possibly delisted; no timezone found
$HFC: possibly delisted; no timezone found
$NXGN: possibly delisted; no timezone found
$AGR: possibly delisted; no timezone found
$CNSL: possibly delisted; no timezone found
$XLRN: possibly delisted; no timezone found
$GLS: possibly delisted; no timezone found
$OLO: possibly delisted; no timezone found
$IGT: possibly delisted; no timezone found
$AMRS: possibly delisted; no timezone found

10 Failed downloads:
['FRC', 'HFC', 'NXGN', 'AGR', 'CNSL', 'XLRN', 'GLS', 'OLO', 'IGT', 'AMRS']: possibly delisted; no timezone found


  Batch 50/81: 15030 rows, 10 tickers


$CIR: possibly delisted; no timezone found
$DZSI: possibly delisted; no timezone found
$SPTN: possibly delisted; no timezone found
$STL: possibly delisted; no timezone found
$OMP: possibly delisted; no timezone found
$SRC: possibly delisted; no timezone found
$AAN: possibly delisted; no timezone found
$CONE: possibly delisted; no timezone found
$ARCE: possibly delisted; no timezone found

9 Failed downloads:
['CIR', 'DZSI', 'SPTN', 'STL', 'OMP', 'SRC', 'AAN', 'CONE', 'ARCE']: possibly delisted; no timezone found


  Batch 51/81: 13280 rows, 11 tickers


$ALIM: possibly delisted; no timezone found
$CRY: possibly delisted; no price data found  (1d 2017-01-01 -> 2024-01-01) (Yahoo error = "Data doesn't exist for startDate = 1483246800, endDate = 1704085200")
$GCP: possibly delisted; no timezone found
$AERI: possibly delisted; no timezone found
$TUP: possibly delisted; no timezone found
$NATI: possibly delisted; no timezone found
$HA: possibly delisted; no timezone found
$PWFL): possibly delisted; no timezone found
$ESTA): possibly delisted; no timezone found

9 Failed downloads:
['ALIM', 'GCP', 'AERI', 'TUP', 'NATI', 'HA', 'PWFL)', 'ESTA)']: possibly delisted; no timezone found
['CRY']: possibly delisted; no price data found  (1d 2017-01-01 -> 2024-01-01) (Yahoo error = "Data doesn't exist for startDate = 1483246800, endDate = 1704085200")


  Batch 52/81: 17456 rows, 11 tickers


$MF: possibly delisted; no timezone found
$VSTA: possibly delisted; no timezone found
$UROV: possibly delisted; no timezone found
$ZUO: possibly delisted; no timezone found

4 Failed downloads:
['MF', 'VSTA', 'UROV', 'ZUO']: possibly delisted; no timezone found


  Batch 53/81: 25040 rows, 16 tickers


$IBTX: possibly delisted; no timezone found
$ODP: possibly delisted; no timezone found
$CDMO: possibly delisted; no timezone found
$ABMD: possibly delisted; no timezone found
$MYTE: possibly delisted; no timezone found
$MANT: possibly delisted; no timezone found
$GES: possibly delisted; no timezone found
$CMA: possibly delisted; no timezone found
$CPSI: possibly delisted; no timezone found
$DRNA: possibly delisted; no timezone found
$STAR: possibly delisted; no timezone found
$ATCO: possibly delisted; no timezone found
$MOR: possibly delisted; no timezone found
$FYBR: possibly delisted; no timezone found

14 Failed downloads:
['IBTX', 'ODP', 'CDMO', 'ABMD', 'MYTE', 'MANT', 'GES', 'CMA', 'CPSI', 'DRNA', 'STAR', 'ATCO', 'MOR', 'FYBR']: possibly delisted; no timezone found


  Batch 54/81: 9290 rows, 6 tickers


$NGD: possibly delisted; no timezone found
$ALEX: possibly delisted; no timezone found
$AVYA: possibly delisted; no timezone found
$IAA: possibly delisted; no timezone found
$DISH: possibly delisted; no timezone found
$DISCA: possibly delisted; no timezone found

6 Failed downloads:
['NGD', 'ALEX', 'AVYA', 'IAA', 'DISH', 'DISCA']: possibly delisted; no timezone found


  Batch 55/81: 21349 rows, 14 tickers


$SWI: possibly delisted; no timezone found
$LANC: possibly delisted; no price data found  (1d 2017-01-01 -> 2024-01-01)
$ONCT: possibly delisted; no timezone found
$HMPT: possibly delisted; no timezone found
$BCOR: possibly delisted; no price data found  (1d 2017-01-01 -> 2024-01-01) (Yahoo error = "Data doesn't exist for startDate = 1483246800, endDate = 1704085200")
$WBK: possibly delisted; no timezone found
$TGP: possibly delisted; no timezone found
$SAND: possibly delisted; no timezone found
$VBTX: possibly delisted; no timezone found

9 Failed downloads:
['SWI', 'ONCT', 'HMPT', 'WBK', 'TGP', 'SAND', 'VBTX']: possibly delisted; no timezone found
['LANC']: possibly delisted; no price data found  (1d 2017-01-01 -> 2024-01-01)
['BCOR']: possibly delisted; no price data found  (1d 2017-01-01 -> 2024-01-01) (Yahoo error = "Data doesn't exist for startDate = 1483246800, endDate = 1704085200")


  Batch 56/81: 17440 rows, 11 tickers


$YELL: possibly delisted; no timezone found
$HTA: possibly delisted; no timezone found
$ERF: possibly delisted; no timezone found
$AQUA: possibly delisted; no timezone found

4 Failed downloads:
['YELL', 'HTA', 'ERF', 'AQUA']: possibly delisted; no timezone found


  Batch 57/81: 26637 rows, 16 tickers


$CPL: possibly delisted; no timezone found
$BXS: possibly delisted; no timezone found
$HEES: possibly delisted; no timezone found
$JBT: possibly delisted; no timezone found
$TCS: possibly delisted; no timezone found
$GPX: possibly delisted; no timezone found

6 Failed downloads:
['CPL', 'BXS', 'HEES', 'JBT', 'TCS', 'GPX']: possibly delisted; no timezone found


  Batch 58/81: 21440 rows, 14 tickers


$GLUU: possibly delisted; no timezone found
$PXD: possibly delisted; no timezone found
$WOLF: possibly delisted; no price data found  (1d 2017-01-01 -> 2024-01-01) (Yahoo error = "Data doesn't exist for startDate = 1483246800, endDate = 1704085200")
$SPR: possibly delisted; no timezone found
$SQSP: possibly delisted; no timezone found
$NBEV: possibly delisted; no timezone found
$RUTH: possibly delisted; no timezone found
$OPB: possibly delisted; no timezone found
$MDP: possibly delisted; no timezone found
$ROIC: possibly delisted; no timezone found

10 Failed downloads:
['GLUU', 'PXD', 'SPR', 'SQSP', 'NBEV', 'RUTH', 'OPB', 'MDP', 'ROIC']: possibly delisted; no timezone found
['WOLF']: possibly delisted; no price data found  (1d 2017-01-01 -> 2024-01-01) (Yahoo error = "Data doesn't exist for startDate = 1483246800, endDate = 1704085200")


  Batch 59/81: 17600 rows, 10 tickers


$OCFT: possibly delisted; no timezone found
$WLTW: possibly delisted; no timezone found
$OCN: possibly delisted; no timezone found
$CEL: possibly delisted; no timezone found
$UCBI: possibly delisted; no timezone found
$PPD: possibly delisted; no timezone found
$X: possibly delisted; no timezone found
$BEDU: possibly delisted; no timezone found
$IBA: possibly delisted; no timezone found

9 Failed downloads:
['OCFT', 'WLTW', 'OCN', 'CEL', 'UCBI', 'PPD', 'X', 'BEDU', 'IBA']: possibly delisted; no timezone found


  Batch 60/81: 17874 rows, 11 tickers


$VG: possibly delisted; no price data found  (1d 2017-01-01 -> 2024-01-01) (Yahoo error = "Data doesn't exist for startDate = 1483246800, endDate = 1704085200")
$APTV): possibly delisted; no timezone found
$PDCE: possibly delisted; no timezone found
$NLS: possibly delisted; no timezone found
$MCFE: possibly delisted; no timezone found
$CSWI: possibly delisted; no timezone found
$APR: possibly delisted; no timezone found

7 Failed downloads:
['VG']: possibly delisted; no price data found  (1d 2017-01-01 -> 2024-01-01) (Yahoo error = "Data doesn't exist for startDate = 1483246800, endDate = 1704085200")
['APTV)', 'PDCE', 'NLS', 'MCFE', 'CSWI', 'APR']: possibly delisted; no timezone found


  Batch 61/81: 20299 rows, 13 tickers


$KSU: possibly delisted; no timezone found
$BRFS: possibly delisted; no timezone found
$MNTV: possibly delisted; no timezone found
$HMTV: possibly delisted; no timezone found
$PRFT: possibly delisted; no timezone found
$SPPI: possibly delisted; no timezone found
$DFS: possibly delisted; no timezone found
$MGP: possibly delisted; no timezone found
$BBL: possibly delisted; no timezone found
$NSTG: possibly delisted; no timezone found
$HZN: possibly delisted; no timezone found

11 Failed downloads:
['KSU', 'BRFS', 'MNTV', 'HMTV', 'PRFT', 'SPPI', 'DFS', 'MGP', 'BBL', 'NSTG', 'HZN']: possibly delisted; no timezone found


  Batch 62/81: 15624 rows, 9 tickers


$MPW: possibly delisted; no timezone found
$TFFP: possibly delisted; no timezone found
$FANH: possibly delisted; no timezone found
$RDS.A: possibly delisted; no timezone found
$AFYA): possibly delisted; no timezone found
$SIX: possibly delisted; no timezone found

6 Failed downloads:
['MPW', 'TFFP', 'FANH', 'RDS.A', 'AFYA)', 'SIX']: possibly delisted; no timezone found


  Batch 63/81: 21102 rows, 14 tickers


$THS: possibly delisted; no timezone found
$MSP: possibly delisted; no timezone found
$GPL: possibly delisted; no timezone found
$RCM: possibly delisted; no timezone found

4 Failed downloads:
['THS', 'MSP', 'GPL', 'RCM']: possibly delisted; no timezone found


  Batch 64/81: 25886 rows, 16 tickers


$HUD: possibly delisted; no timezone found
$FGEN: possibly delisted; no timezone found
$USM: possibly delisted; no timezone found
$CDAY: possibly delisted; no timezone found
$RCII: possibly delisted; no timezone found
$SGH: possibly delisted; no timezone found
$SKX: possibly delisted; no timezone found
$EVA: possibly delisted; no timezone found
$ZEN: possibly delisted; no timezone found
$BECN: possibly delisted; no timezone found

10 Failed downloads:
['HUD', 'FGEN', 'USM', 'CDAY', 'RCII', 'SGH', 'SKX', 'EVA', 'ZEN', 'BECN']: possibly delisted; no timezone found


  Batch 65/81: 16732 rows, 10 tickers


$LGF-A: possibly delisted; no timezone found
$NLSN: possibly delisted; no timezone found
$ATNX: possibly delisted; no timezone found
$KAR: possibly delisted; no timezone found
$AVLR: possibly delisted; no timezone found
$FLXN: possibly delisted; no price data found  (1d 2017-01-01 -> 2024-01-01) (Yahoo error = "Data doesn't exist for startDate = 1483246800, endDate = 1704085200")
$HCRS.Q: possibly delisted; no timezone found
$MMP: possibly delisted; no timezone found
$BVN): possibly delisted; no timezone found
$ESMT: possibly delisted; no timezone found
$BRY: possibly delisted; no timezone found
$ISEE: possibly delisted; no timezone found

12 Failed downloads:
['LGF-A', 'NLSN', 'ATNX', 'KAR', 'AVLR', 'HCRS.Q', 'MMP', 'BVN)', 'ESMT', 'BRY', 'ISEE']: possibly delisted; no timezone found
['FLXN']: possibly delisted; no price data found  (1d 2017-01-01 -> 2024-01-01) (Yahoo error = "Data doesn't exist for startDate = 1483246800, endDate = 1704085200")


  Batch 66/81: 12803 rows, 8 tickers


$ATVI: possibly delisted; no timezone found
$OSH: possibly delisted; no timezone found
$ANSS: possibly delisted; no timezone found
$KAMN: possibly delisted; no timezone found
$XLNX: possibly delisted; no timezone found
$GSX: possibly delisted; no price data found  (1d 2017-01-01 -> 2024-01-01) (Yahoo error = "Data doesn't exist for startDate = 1483246800, endDate = 1704085200")
$UIHC: possibly delisted; no timezone found
$HCCI: possibly delisted; no timezone found
$OCDX: possibly delisted; no timezone found
$GHLD: possibly delisted; no timezone found

10 Failed downloads:
['ATVI', 'OSH', 'ANSS', 'KAMN', 'XLNX', 'UIHC', 'HCCI', 'OCDX', 'GHLD']: possibly delisted; no timezone found
['GSX']: possibly delisted; no price data found  (1d 2017-01-01 -> 2024-01-01) (Yahoo error = "Data doesn't exist for startDate = 1483246800, endDate = 1704085200")


  Batch 67/81: 15639 rows, 10 tickers


$TWNK: possibly delisted; no timezone found
$AKTS: possibly delisted; no price data found  (1d 2017-01-01 -> 2024-01-01) (Yahoo error = "Data doesn't exist for startDate = 1483246800, endDate = 1704085200")
$HMSY: possibly delisted; no timezone found
$STON: possibly delisted; no timezone found
$BBU: possibly delisted; no timezone found
$SGFY): possibly delisted; no timezone found
$TVTY: possibly delisted; no timezone found
$ICPT: possibly delisted; no timezone found

8 Failed downloads:
['TWNK', 'HMSY', 'STON', 'BBU', 'SGFY)', 'TVTY', 'ICPT']: possibly delisted; no timezone found
['AKTS']: possibly delisted; no price data found  (1d 2017-01-01 -> 2024-01-01) (Yahoo error = "Data doesn't exist for startDate = 1483246800, endDate = 1704085200")


  Batch 68/81: 21081 rows, 12 tickers


$GMLP: possibly delisted; no timezone found
$NYMT: possibly delisted; no timezone found
$KUKE: possibly delisted; no timezone found
$VTRU: possibly delisted; no timezone found
$NEP: possibly delisted; no timezone found
$FBHS: possibly delisted; no timezone found
$AEL: possibly delisted; no timezone found
$ELP: possibly delisted; no timezone found
$CYBR: possibly delisted; no timezone found

9 Failed downloads:
['GMLP', 'NYMT', 'KUKE', 'VTRU', 'NEP', 'FBHS', 'AEL', 'ELP', 'CYBR']: possibly delisted; no timezone found


  Batch 69/81: 15571 rows, 11 tickers


$HSKA: possibly delisted; no timezone found
$TA: possibly delisted; no timezone found
$WWE: possibly delisted; no timezone found
$ROCC: possibly delisted; no timezone found
$MMC: possibly delisted; no timezone found
$CHNG: possibly delisted; no timezone found
$MNRL: possibly delisted; no timezone found
$PFC: possibly delisted; no timezone found

8 Failed downloads:
['HSKA', 'TA', 'WWE', 'ROCC', 'MMC', 'CHNG', 'MNRL', 'PFC']: possibly delisted; no timezone found


  Batch 70/81: 19417 rows, 12 tickers


$NP: possibly delisted; no price data found  (1d 2017-01-01 -> 2024-01-01) (Yahoo error = "Data doesn't exist for startDate = 1483246800, endDate = 1704085200")
$AKYA): possibly delisted; no timezone found
$KL: possibly delisted; no timezone found
$CSLT: possibly delisted; no timezone found
$HNGR: possibly delisted; no timezone found
$MFGP: possibly delisted; no timezone found
$TRTN: possibly delisted; no timezone found
$ADAP: possibly delisted; no timezone found
$NS: possibly delisted; no timezone found

9 Failed downloads:
['NP']: possibly delisted; no price data found  (1d 2017-01-01 -> 2024-01-01) (Yahoo error = "Data doesn't exist for startDate = 1483246800, endDate = 1704085200")
['AKYA)', 'KL', 'CSLT', 'HNGR', 'MFGP', 'TRTN', 'ADAP', 'NS']: possibly delisted; no timezone found


  Batch 71/81: 14493 rows, 11 tickers


$IMGN: possibly delisted; no timezone found
$EVBG: possibly delisted; no timezone found
$BLI: possibly delisted; no timezone found
$CCXI: possibly delisted; no price data found  (1d 2017-01-01 -> 2024-01-01) (Yahoo error = "Data doesn't exist for startDate = 1483246800, endDate = 1704085200")
$SGFY: possibly delisted; no timezone found
$AMEH: possibly delisted; no timezone found
$SASR: possibly delisted; no timezone found
$PARA: possibly delisted; no timezone found

8 Failed downloads:
['IMGN', 'EVBG', 'BLI', 'SGFY', 'AMEH', 'SASR', 'PARA']: possibly delisted; no timezone found
['CCXI']: possibly delisted; no price data found  (1d 2017-01-01 -> 2024-01-01) (Yahoo error = "Data doesn't exist for startDate = 1483246800, endDate = 1704085200")


  Batch 72/81: 19937 rows, 12 tickers


$AZUL: possibly delisted; no price data found  (1d 2017-01-01 -> 2024-01-01) (Yahoo error = "Data doesn't exist for startDate = 1483246800, endDate = 1704085200")
$ZENV: possibly delisted; no timezone found
$MOG.A: possibly delisted; no timezone found
$SGEN: possibly delisted; no timezone found
$SMTS: possibly delisted; no timezone found
$AJX: possibly delisted; no timezone found

6 Failed downloads:
['AZUL']: possibly delisted; no price data found  (1d 2017-01-01 -> 2024-01-01) (Yahoo error = "Data doesn't exist for startDate = 1483246800, endDate = 1704085200")
['ZENV', 'MOG.A', 'SGEN', 'SMTS', 'AJX']: possibly delisted; no timezone found


  Batch 73/81: 22368 rows, 14 tickers


$TLIS: possibly delisted; no timezone found
$CIB): possibly delisted; no timezone found
$AVID: possibly delisted; no timezone found
$CVAC: possibly delisted; no timezone found
$CCR: possibly delisted; no timezone found
$RE: possibly delisted; no timezone found
$AXNX: possibly delisted; no timezone found
$CIO: possibly delisted; no timezone found
$LTHM: possibly delisted; no timezone found
$CLR: possibly delisted; no timezone found

10 Failed downloads:
['TLIS', 'CIB)', 'AVID', 'CVAC', 'CCR', 'RE', 'AXNX', 'CIO', 'LTHM', 'CLR']: possibly delisted; no timezone found


  Batch 74/81: 13559 rows, 10 tickers


$SAVE: possibly delisted; no timezone found
$SBT: possibly delisted; no timezone found
$WW: possibly delisted; no price data found  (1d 2017-01-01 -> 2024-01-01) (Yahoo error = "Data doesn't exist for startDate = 1483246800, endDate = 1704085200")
$HLMN): possibly delisted; no timezone found
$SPNS: possibly delisted; no timezone found
$SWCH: possibly delisted; no timezone found
$HZNP: possibly delisted; no timezone found
$HIBB: possibly delisted; no timezone found

8 Failed downloads:
['SAVE', 'SBT', 'HLMN)', 'SPNS', 'SWCH', 'HZNP', 'HIBB']: possibly delisted; no timezone found
['WW']: possibly delisted; no price data found  (1d 2017-01-01 -> 2024-01-01) (Yahoo error = "Data doesn't exist for startDate = 1483246800, endDate = 1704085200")


  Batch 75/81: 18606 rows, 12 tickers


$SYX: possibly delisted; no timezone found
$ARCH: possibly delisted; no timezone found
$TMST: possibly delisted; no timezone found
$AL: possibly delisted; no timezone found
$ZIXI: possibly delisted; no timezone found
$TMX: possibly delisted; no timezone found
$SAGE: possibly delisted; no timezone found
$RTN: possibly delisted; no timezone found
$VRNT: possibly delisted; no price data found  (1d 2017-01-01 -> 2024-01-01)
$CAMP: possibly delisted; no price data found  (1d 2017-01-01 -> 2024-01-01) (Yahoo error = "Data doesn't exist for startDate = 1483246800, endDate = 1704085200")

10 Failed downloads:
['SYX', 'ARCH', 'TMST', 'AL', 'ZIXI', 'TMX', 'SAGE', 'RTN']: possibly delisted; no timezone found
['VRNT']: possibly delisted; no price data found  (1d 2017-01-01 -> 2024-01-01)
['CAMP']: possibly delisted; no price data found  (1d 2017-01-01 -> 2024-01-01) (Yahoo error = "Data doesn't exist for startDate = 1483246800, endDate = 1704085200")


  Batch 76/81: 15446 rows, 10 tickers


$TPIC: possibly delisted; no price data found  (1d 2017-01-01 -> 2024-01-01)
$DSKE: possibly delisted; no timezone found
$AAWW: possibly delisted; no timezone found
$AKYA: possibly delisted; no timezone found
$CUB: possibly delisted; no price data found  (1d 2017-01-01 -> 2024-01-01) (Yahoo error = "Data doesn't exist for startDate = 1483246800, endDate = 1704085200")
$NFH: possibly delisted; no timezone found
$PINC: possibly delisted; no price data found  (1d 2017-01-01 -> 2024-01-01)
$IMAB: possibly delisted; no timezone found
$AMK: possibly delisted; no timezone found
$NH: possibly delisted; no timezone found
$KIRK: possibly delisted; no timezone found

11 Failed downloads:
['TPIC', 'PINC']: possibly delisted; no price data found  (1d 2017-01-01 -> 2024-01-01)
['DSKE', 'AAWW', 'AKYA', 'NFH', 'IMAB', 'AMK', 'NH', 'KIRK']: possibly delisted; no timezone found
['CUB']: possibly delisted; no price data found  (1d 2017-01-01 -> 2024-01-01) (Yahoo error = "Data doesn't exist for startDate

  Batch 77/81: 12617 rows, 9 tickers


$WBA: possibly delisted; no timezone found
$CHMA: possibly delisted; no timezone found
$VVNT: possibly delisted; no timezone found
$DNAY: possibly delisted; no timezone found
$DSPG: possibly delisted; no timezone found
$NARI: possibly delisted; no timezone found
$LTRPA: possibly delisted; no timezone found

7 Failed downloads:
['WBA', 'CHMA', 'VVNT', 'DNAY', 'DSPG', 'NARI', 'LTRPA']: possibly delisted; no timezone found


  Batch 78/81: 22880 rows, 13 tickers


$POLY: possibly delisted; no timezone found
$SEAS: possibly delisted; no timezone found
$MGI: possibly delisted; no timezone found
$BIGC: possibly delisted; no timezone found
$PRO: possibly delisted; no timezone found
$TRQ: possibly delisted; no timezone found
$MDC: possibly delisted; no timezone found
$EPAY: possibly delisted; no timezone found
$JNCE: possibly delisted; no timezone found
$VOXX: possibly delisted; no timezone found
$KRT): possibly delisted; no timezone found
$EXAS: possibly delisted; no timezone found

12 Failed downloads:
['POLY', 'SEAS', 'MGI', 'BIGC', 'PRO', 'TRQ', 'MDC', 'EPAY', 'JNCE', 'VOXX', 'KRT)', 'EXAS']: possibly delisted; no timezone found


  Batch 79/81: 12570 rows, 8 tickers


$RETA: possibly delisted; no timezone found
$TWOU: possibly delisted; no timezone found
$OSTK: possibly delisted; no timezone found
$GCI: possibly delisted; no timezone found
$CTLT: possibly delisted; no timezone found
$ZIMV: possibly delisted; no timezone found
$SCWX: possibly delisted; no timezone found
$GPS: possibly delisted; no timezone found

8 Failed downloads:
['RETA', 'TWOU', 'OSTK', 'GCI', 'CTLT', 'ZIMV', 'SCWX', 'GPS']: possibly delisted; no timezone found


  Batch 80/81: 20209 rows, 12 tickers


$DCP: possibly delisted; no timezone found

1 Failed download:
['DCP']: possibly delisted; no timezone found


  Batch 81/81: 1185 rows, 1 tickers

Re-fetch complete.
  Batches with data:  81
  Still failed:       0 tickers

New price rows fetched: 1435241
New tickers fetched:    920

Updated price data:
  Total rows:    3559854
  Total tickers: 2194

Saved: Data/stock_prices_updated.csv
Rebuilt price_by_ticker with 2194 tickers


In [30]:
# ── Re-run join with updated price_by_ticker ─────────────────────────────────

results = []
skipped = 0

print("Re-running join with updated price data...")

for idx, row in df.iterrows():
    ticker   = row['ticker']
    earn_date = row['earnings_date']

    if ticker not in price_by_ticker:
        skipped += 1
        continue

    prices = price_by_ticker[ticker]

    try:
        base_price = None
        for offset in range(6):
            lookup = earn_date + pd.Timedelta(days=offset)
            if lookup in prices.index:
                base_price = prices[lookup]
                break

        if base_price is None or pd.isna(base_price) or base_price == 0:
            skipped += 1
            continue

        price_5d  = get_nth_trading_day_price(prices, earn_date, 5)
        price_10d = get_nth_trading_day_price(prices, earn_date, 10)
        price_20d = get_nth_trading_day_price(prices, earn_date, 20)

        return_5d  = (price_5d  / base_price - 1) if not pd.isna(price_5d)  else np.nan
        return_10d = (price_10d / base_price - 1) if not pd.isna(price_10d) else np.nan
        return_20d = (price_20d / base_price - 1) if not pd.isna(price_20d) else np.nan

        results.append({
            'idx'       : idx,
            'base_price': base_price,
            'price_5d'  : price_5d,
            'price_10d' : price_10d,
            'price_20d' : price_20d,
            'return_5d' : return_5d,
            'return_10d': return_10d,
            'return_20d': return_20d,
            'label_5d'  : 1 if return_5d  > 0 else 0 if not pd.isna(return_5d)  else np.nan,
            'label_10d' : 1 if return_10d > 0 else 0 if not pd.isna(return_10d) else np.nan,
            'label_20d' : 1 if return_20d > 0 else 0 if not pd.isna(return_20d) else np.nan,
        })

    except Exception as e:
        skipped += 1
        continue

print(f"Successfully computed returns: {len(results)}")
print(f"Skipped (no price data):       {skipped}")

Re-running join with updated price data...
Successfully computed returns: 14857
Skipped (no price data):       3898


In [31]:
# ── Merge results back into main dataframe ────────────────────────────────────

results_df = pd.DataFrame(results).set_index('idx')

# Drop old return columns to avoid conflicts from previous run
for col in ['return_5d', 'return_10d', 'return_20d',
            'label_5d', 'label_10d', 'label_20d',
            'base_price', 'price_5d', 'price_10d', 'price_20d']:
    if col in df.columns:
        df = df.drop(columns=[col])

df = df.join(results_df)
df_final = df.dropna(subset=['return_5d', 'return_10d', 'return_20d']).copy()

print(f"Final usable tickers: {df_final['ticker'].nunique()}")
print(f"Final usable rows:    {len(df_final)}")

print(f"\nLabel distribution (5-day):")
print(df_final['label_5d'].value_counts())
print(f"\nLabel distribution (10-day):")
print(df_final['label_10d'].value_counts())
print(f"\nLabel distribution (20-day):")
print(df_final['label_20d'].value_counts())

print(f"\nReturn summary:")
print(df_final[['return_5d', 'return_10d', 'return_20d']].describe())

Final usable tickers: 2187
Final usable rows:    14857

Label distribution (5-day):
label_5d
1.0    7825
0.0    7032
Name: count, dtype: int64

Label distribution (10-day):
label_10d
1.0    7759
0.0    7098
Name: count, dtype: int64

Label distribution (20-day):
label_20d
1.0    7925
0.0    6932
Name: count, dtype: int64

Return summary:
          return_5d    return_10d    return_20d
count  14857.000000  14857.000000  14857.000000
mean       0.004419      0.003616      0.008983
std        0.091813      0.112036      0.157555
min       -0.568147     -0.636631     -0.701413
25%       -0.037986     -0.050943     -0.063466
50%        0.004002      0.004060      0.007872
75%        0.045142      0.055718      0.077509
max        0.941176      2.162420      4.663415


**Fetch Financial Fundamentals via yfinance**

In [32]:
print("Fetching financial fundamentals for usable tickers...")

usable_tickers = df_final['ticker'].unique().tolist()
fundamentals   = []
failed_fundamentals = []

for i, ticker in enumerate(usable_tickers):
    try:
        t = yf.Ticker(ticker)
        info = t.info

        # Guard against empty or invalid info response
        if not info or len(info) == 0:
            failed_fundamentals.append(ticker)
            continue

        # Guard against info returning only metadata with no financial fields
        if 'marketCap' not in info and 'totalRevenue' not in info:
            failed_fundamentals.append(ticker)
            continue

        fundamentals.append({
            'ticker':            ticker,
            'sector':            info.get('sector',             np.nan),
            'industry':          info.get('industry',           np.nan),
            'market_cap':        info.get('marketCap',          np.nan),
            'pe_ratio':          info.get('trailingPE',         np.nan),
            'forward_pe':        info.get('forwardPE',          np.nan),
            'eps_trailing':      info.get('trailingEps',        np.nan),
            'eps_forward':       info.get('forwardEps',         np.nan),
            'revenue':           info.get('totalRevenue',       np.nan),
            'gross_margin':      info.get('grossMargins',       np.nan),
            'operating_margin':  info.get('operatingMargins',   np.nan),
            'profit_margin':     info.get('profitMargins',      np.nan),
            'debt_to_equity':    info.get('debtToEquity',       np.nan),
            'return_on_equity':  info.get('returnOnEquity',     np.nan),
            'return_on_assets':  info.get('returnOnAssets',     np.nan),
            'beta':              info.get('beta',               np.nan),
            'fifty_two_wk_high': info.get('fiftyTwoWeekHigh',  np.nan),
            'fifty_two_wk_low':  info.get('fiftyTwoWeekLow',   np.nan),
        })

        if (i + 1) % 50 == 0:
            print(f"  Fetched {i + 1}/{len(usable_tickers)} tickers...")
            time.sleep(2)
        else:
            time.sleep(0.3)

    except Exception as e:
        failed_fundamentals.append(ticker)
        continue

fundamentals_df = pd.DataFrame(fundamentals)
fundamentals_df.to_csv('Data/fundamentals.csv', index=False)

print(f"\nFundamentals fetched:  {len(fundamentals_df)} tickers")
print(f"Failed:                {len(failed_fundamentals)} tickers")
print(f"Sector distribution:\n{fundamentals_df['sector'].value_counts().head(10)}")
print("\nSaved: Data/fundamentals.csv")

Fetching financial fundamentals for usable tickers...
  Fetched 50/2187 tickers...
  Fetched 100/2187 tickers...
  Fetched 150/2187 tickers...
  Fetched 200/2187 tickers...
  Fetched 250/2187 tickers...
  Fetched 300/2187 tickers...
  Fetched 350/2187 tickers...
  Fetched 400/2187 tickers...
  Fetched 450/2187 tickers...
  Fetched 500/2187 tickers...
  Fetched 550/2187 tickers...
  Fetched 600/2187 tickers...
  Fetched 650/2187 tickers...
  Fetched 700/2187 tickers...
  Fetched 750/2187 tickers...
  Fetched 800/2187 tickers...
  Fetched 850/2187 tickers...
  Fetched 900/2187 tickers...
  Fetched 950/2187 tickers...
  Fetched 1000/2187 tickers...
  Fetched 1050/2187 tickers...
  Fetched 1100/2187 tickers...
  Fetched 1150/2187 tickers...
  Fetched 1200/2187 tickers...
  Fetched 1250/2187 tickers...
  Fetched 1300/2187 tickers...
  Fetched 1350/2187 tickers...
  Fetched 1400/2187 tickers...
  Fetched 1450/2187 tickers...
  Fetched 1500/2187 tickers...
  Fetched 1550/2187 tickers...
  Fet

**Ticker Standardization and Final Filter**

In [33]:
print("Applying final filters...")

# ── Standardize ticker symbols before filtering ──────────────────────────────────────
def standardize_ticker(ticker):
    return str(ticker).strip().upper().replace('.', '-')

df_final['ticker'] = df_final['ticker'].apply(standardize_ticker)
price_df['ticker'] = price_df['ticker'].apply(standardize_ticker)
print("Ticker symbols standardized (e.g. BRK.B → BRK-B)")

# ── Filter to tickers with at least 2 quarters of transcript data ────────────────────
ticker_counts = df_final.groupby('ticker')['q'].nunique()
tickers_2plus = ticker_counts[ticker_counts >= 2].index
df_final = df_final[df_final['ticker'].isin(tickers_2plus)].copy()

print(f"Tickers with 2+ quarters: {df_final['ticker'].nunique()}")
print(f"Rows after filter:        {len(df_final)}")

# ── Check temporal distribution ──────────────────────────────────────────────────────
df_final['year'] = pd.to_datetime(df_final['earnings_date']).dt.year
print(f"\nRows by year:")
print(df_final['year'].value_counts().sort_index())

# ── Train/test split preview (2019-2021 train, 2022-2023 test) ───────────────────────
train = df_final[df_final['year'].isin([2019, 2020, 2021])]
test  = df_final[df_final['year'].isin([2022, 2023])]
print(f"\nTrain set (2019-2021): {len(train)} rows, {train['ticker'].nunique()} tickers")
print(f"Test set  (2022-2023): {len(test)} rows,  {test['ticker'].nunique()} tickers")

# ── Save filtered dataset after 2+ quarters filter ───────────────────────────────────
existing_cols = [c for c in cols_to_save if c in df_final.columns]
df_final[existing_cols].to_csv('Data/cleaned_transcripts_final.csv', index=False)
print(f"\nSaved: Data/cleaned_transcripts_final.csv")
print(f"  Rows: {len(df_final)}")
print(f"  Tickers: {df_final['ticker'].nunique()}")

Applying final filters...
Ticker symbols standardized (e.g. BRK.B → BRK-B)
Tickers with 2+ quarters: 2078
Rows after filter:        14738

Rows by year:
year
2017      14
2018     220
2019    1075
2020    2179
2021    7577
2022    3490
2023     183
Name: count, dtype: int64

Train set (2019-2021): 10831 rows, 2052 tickers
Test set  (2022-2023): 3673 rows,  1031 tickers

Saved: Data/cleaned_transcripts_final.csv
  Rows: 14738
  Tickers: 2078


**Final Summary**

In [34]:
print("=" * 60)
print("PHASE 1 COMPLETE")
print("=" * 60)
print(f"Final dataset:  {len(df_final)} rows")
print(f"Unique tickers: {df_final['ticker'].nunique()}")
print(f"Date range:     {df_final['earnings_date'].min()} to {df_final['earnings_date'].max()}")
print(f"Train rows:     {len(train)}")
print(f"Test rows:      {len(test)}")
print(f"\nFiles saved:")
print(f"  Data/cleaned_transcripts_final.csv — main handoff file for Phase 2")
print(f"  Data/stock_prices_updated.csv      — full price history")
print(f"  Data/sp500_prices.csv              — S&P 500 benchmark")
print(f"  Data/fundamentals.csv              — financial fundamentals")
print("=" * 60)

PHASE 1 COMPLETE
Final dataset:  14738 rows
Unique tickers: 2078
Date range:     2017-10-01 00:00:00 to 2023-02-23 00:00:00
Train rows:     10831
Test rows:      3673

Files saved:
  Data/cleaned_transcripts_final.csv — main handoff file for Phase 2
  Data/stock_prices_updated.csv      — full price history
  Data/sp500_prices.csv              — S&P 500 benchmark
  Data/fundamentals.csv              — financial fundamentals


**Phase 1 Complete — Re-fetch Results and Final Dataset Summary:**
- The initial price data collection retrieved 1,274 tickers due to yfinance rate limiting, resulting in only 9,599 matched transcript rows. 
- Following the re-fetch using smaller batch sizes (20 tickers) and longer pauses (10 seconds), an additional 920 tickers were successfully recovered with 1,435,241 new price rows, expanding the total price universe from 1,274 to 2,194 tickers with zero remaining failures. 
- After re-running the transcript-to-price join with the updated data, the final dataset grew from 9,599 to **14,857 matched rows**, a 55% increase. 
- After applying the 2+ quarters filter to ensure each ticker has sufficient temporal coverage for training, the final handoff dataset `cleaned_transcripts_final.csv` contains **14,738 rows across 2,078 unique tickers**, spanning October 2017 to February 2023. 
- The label distribution is well-balanced across all three return horizons, approximately 52% positive and 48% negative for the 5-day label, indicating no class imbalance issues for downstream ML training. 
- The temporal train/test split yields 10,831 training rows (2019–2021) and 3,673 test rows (2022–2023), with sector coverage representative of the broader market including Technology (354 tickers), Healthcare (326), Financial Services (296), Consumer Cyclical (281), and Industrials (275). 
- Financial fundamentals were successfully fetched for 2,186 of 2,187 tickers and saved separately in `fundamentals.csv` for use in the dashboard and benchmarking modules in later phases.